### ISSUE TITLE
auro-input: create blueprint for "text area" input

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-input#105]
## Is your feature request related to a problem? Please describe.

Text input field with ability to write multiple lines is needed.

## Describe the solution you'd like

Create blueprint for new input text area, add in either as variant of input or a completely separate component.

**Comment by braven112** [comment]
Closing this duplicate in favor of this issue.
https://github.com/AlaskaAirlines/auro/issues/253
