### ISSUE TITLE
"novalidate" attribute not respected after error set

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-input#107]
## Describe the bug

If you set an error on an input with the "novalidate" attribute set, the built-in validation will start running after the manual error is removed.

## To Reproduce

Consider the following example:

```html
<auro-input label="Test" required novalidate></auro-input>
```

```js
const input = document.querySelector('auro-input');

input.addEventListener('input', (e) => {
    if (e.target.value.match(/[0-9]+/)) {
        input.error = "No numbers allowed";
    } else {
        input.error = null;
    }
});
```

1. Enter numbers into the input. The custom error message is displayed
2. Remove all text in the input. The custom error message is removed, but the component is still in an error state because the internal validation started running.

## Expected behavior

Novalidate is respected and the component does not perform any built-in validation, even if the error attribute was set and removed.

**Comment by blackfalcon** [comment]
@geoffrich can you create a branch of the element with an updated demo that illustrates this? I 'think' I understand the issue, but I am not 100%.

**Comment by geoffrich** [comment]
@blackfalcon I'll do you one better -- made a branch with a failing test and a PR to fix it. This test failed before the changes in my PR.

https://github.com/AlaskaAirlines/auro-input/blob/f1d00af850881f4d641a47bf4f6bbd11233bcc37/test/auro-input.test.js#L168-L178
