### ISSUE TITLE
Need true borderless version of input UI

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-input#110]
## Is your feature request related to a problem? Please describe.

Need to support a borderless (including the underline border) of the input. The current use case for this is within `auro-suggest` where the `auro-dropdown` will handle all the borders and styles for it.

## Describe the solution you'd like

Add a `borderless` attribute that removes all border styles from `auro-input`.

**Comment by leeejune** [comment]
I will not be adding this to the UI kit for designers because it seems like this is a engineering thing more than a design tool!

**Comment by leeejune** [comment]
@jason-capsule42 Do you still need design support on this?
