### ISSUE TITLE
Allow commercial cards in credit-card input type

### ISSUE THREAD

**Issue by Chris-Boe** [AlaskaAirlines/auro-input#112]
## Is your feature request related to a problem? Please describe.

Commercial card numbers are not supported.

These have a length of 11, which is not supported by the validation pattern and they don't have a card icon

## Describe the solution you'd like

Validation of 11 digit card number lengths, when the card number starts with  “27”.

A card icon would also be nice but can be secondary

## Describe alternatives you've considered

None, this is a requirement on most of Alaska's interaction with credit cards. The only place commercial cards are not supported that I know of is Pre-Order.

## Exit Criteria 

See https://github.com/AlaskaAirlines/auro-input/issues/112#issuecomment-1061296084 for full explanation.

This feature will be considered complete once a new rule-set supports the use of a `2` as the first digit to reduce the scope of validated digits to `7`. In addition, a rule must be set to support the showing of the Alaska card icon when the first two digits are `27`. 

In addition to the functional requirement, documents/demos need to be updated that includes information to support the general credit card support cases, amex as a special case card, and all other credit card icons when the `icon` attribute is used.

**Comment by blackfalcon** [comment]
Adding in a new card-digit rule is a feature that can be added to the logic of this element. The additional icon requested is a design request and the card icon would need to be added to the Auro Icons repo in order be picked up by the auro-icon element.

**Comment by blackfalcon** [comment]
In addition to this work, the *exit criteria* should include doc updates that describe the rules that govern credit card use.

**Comment by blackfalcon** [comment]
I had a conversation with @Chris-Boe as to the actual specification for this update.

`2` === Airlines and other future industry assignments (2*****)
`27` === special assignment to Alasksa Airlines 

The core of the ask is to allow support for a corp card and validate at `11` digits versus the `15`/`16` of other cards

The concept of `11` digits is not a fixed concept for corp cards. With the addition of an individual account identification number and a single-digit checksum, the range will vary.

> An IIN is currently six digits in length. The leading digit is the major industry identifier (MII), followed by 5 digits, which together make up the IIN. This IIN is paired with an individual account identification number, and a single digit checksum.

The recommendation for this feature is the following;

1. When the digit starts with a `2` reduce entry validation to `7`. Account for the `2`, plus the next `5` expected and a single space, this is the minimum number of digits per the spec, all other digits pertain to card issuer and account.
1. When the digits start with a `27` update icon to show Alaska credit card, this is a fixed number assigned to Alaska. 

The spec for this issue will be updated accordingly.
