### ISSUE TITLE
Support Diner's Club and Universal Air Travel Plan number formats

### ISSUE THREAD

**Issue by Chris-Boe** [AlaskaAirlines/auro-input#125]
## Is your feature request related to a problem? Please describe.
Many workflows that use the auro-input Credit Card component need to allow differently formatted credit card numbers like the Diner's Club (14 digits, starting with 36, 38, or 300 thru 305, and formatted like 3852 000002 3237) or Universal Air Travel Plan (15 digits, starting with a 1 or 2 and formatted like 1533 42999 757575)

## Describe the solution you'd like
Might be resolved by #122 - a client configurable card number validation schema

## Describe alternatives you've considered
Replacing the component with a custom input component

## Additional context
From AS.com, it seems Diner's Club should be storable and accepted by all transaction types, while UATP should only be storable and used for flight purchases.

**Comment by blackfalcon** [comment]
This is a bug, not a feature. 

The fact is that we support these card types, but our validation solution is not allowing them to be valid. 

<img width="584" alt="Screen Shot 2022-03-17 at 7 51 51 AM" src="https://user-images.githubusercontent.com/181089/158830979-2ac81b8b-41a4-476e-b8a2-4d032a060296.png">

The scope of this update is to address the missing validation types to allow for the processing of the data.
