### ISSUE TITLE
credit-card input doesn't flip isValid flag after last key stroke

### ISSUE THREAD

**Issue by DZwell** [AlaskaAirlines/auro-input#128]
## Describe the bug
The credit card input field doesn't validate after the last keystroke like the other input fields. I have the "Continue" button wired up to listen to the `isValid` property of all auro-input fields and disable it when any of them have `isValid` as `false`. You can see from the GIF the button responds to the expiration date and name on card fields but _not_ the credit card field.

![credit-card-input](https://user-images.githubusercontent.com/10947475/160694590-8c4b08a9-8291-486b-a03c-2e6511fac340.gif)

## To Reproduce
1. Enter valid card number

## Expected behavior

Credit card field should behave like other auro-input fields in regards to validation

## Desktop (please complete the following information):

 - Browser: Chrome

**Comment by blackfalcon** [comment]
Digging into this issue, the primary problem we are having is a combination of when the event fires and the restriction on characters allowed for a credit card. 

E.g., when using a corp card, the restriction addresses the validation BEFORE the maxLength is met. That means that the next event can be fired and the bit flipped. 

In the case where we are not flipping the validation until the last character allowed is typed, there is no room for the event to fire. So, changing the event listener is the current recommendation. Using the `keyup` event versus a `change` or `input` event addresses this restriction. 

The following code was used with the demo page to track the event, the `isValid` state and the `aria-invalid` value. 

```js
        const source = document.getElementById('demo11');

        const inputHandler = function(e) {
          console.log(e);
          console.log('isValid? ' + source.isValid);
          console.log('aria-invalid = ' + e.target.shadowRoot.getElementById('demo11').getAttribute('aria-invalid'));
        }

        source.addEventListener('keyup', inputHandler);
```
