### ISSUE TITLE
Only show the X clear icon if the input has a value

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-input#131]
## Is your feature request related to a problem? Please describe.

Only show the X clear icon if the input has a value

## Describe the solution you'd like

Currently the X icon to clear the value shows up the moment the input has focus regardless of the value of the input

We should only show the clear button when there is a value to clear.

**Comment by blackfalcon** [comment]
I am assigning this to @leeejune to discuss with @jason-capsule42 and the other UI designers. The current state of the input was dictated by the original design. Not to say that this can't be updated, but the current UI/UX is operating as designed.

**Comment by blackfalcon** [comment]
I am labeling this as BLOCKED as there needs to be a conversation prior to a suggested resolution.

**Comment by blackfalcon** [comment]
Outdated requiest.
