### ISSUE TITLE
Support full-name type input field

### ISSUE THREAD

**Issue by DZwell** [AlaskaAirlines/auro-input#133]
## Is your feature request related to a problem? Please describe.
Yes, see [this issue](https://github.com/AlaskaAirlines/auro-input/issues/132)

Full name is a very common use case, it would be great if Auro had this functionality built in to the auro-input.

## Describe the solution you'd like
Have auro-input validate a full-name scenario out of the box.

## Describe alternatives you've considered
Use the `pattern` property with custom regex.
This is the regex pattern we're using: `[a-zA-Z-.']+( +[a-zA-Z-.']+)+` it captures a group of characters followed by at least one whitespace and another group of characters. It also includes a few special chars like `-.'`

**Comment by blackfalcon** [comment]
I am moving this to READY TO WORK so that we don't lose sight of this issue, but it's not 100% confirmed that we will be adopting this as a pre-defined type.

**Comment by blackfalcon** [comment]
After some reflection, I am not seeing the value in this update that I initially did. Owning this pattern puts the onus on the Auro team to also maintain this and thus allow for customization if a team needs a different regex for the name pattern. That in itself states that we should not own that entirely. 

The update for #132 effectively addresses this need and the demo example allows for a standard regex to be used, but easily customized in use if needed.
