### ISSUE TITLE
Editing a date input jumps the cursor to the end of the input

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-input#146]
## Describe the bug

When I enter a new character in a date input or remove a character with backspace, the cursor jumps to the end of the input with every keystroke.

## To Reproduce

1. Go to [auro-input](https://auro.alaskaair.com/components/auro/input) on the doc site and scroll to "date input"
1. Type in "01/03/2022"
1. Click after the 3 and hit backspace. The cursor jumps to the end of the input.
2. Click after "/0" and enter 3 again. The cursor jumps to the end of the input

## Expected behavior

The cursor does not jump to the end of the input.

## Screenshots

![date](https://user-images.githubusercontent.com/4992896/167697260-f7de647e-62f9-4ea1-b238-67963eb77988.gif)

## Desktop (please complete the following information):

 - OS: Windows 10
 - Browser: Chrome and Firefox

## Smartphone (please complete the following information):

n/a

**Comment by blackfalcon** [comment]
This is a never-ending issue with this element. There have been multiple things done to try and negate this issue with the ever-growing complexity. 

I fear that this will be a rabbit hole of fix/break work. 

I stress that we must consider breaking up this element into individual sub-elements per their specific experiences.

**Comment by blackfalcon** [comment]
I marked this as `blocked` so that this is NOT worked on prior to the systematic breakup of the auro-input element.

**Comment by Patrick-Daly-AA** [comment]
To be validated in the DatePicker Beta Branch to see if this is still an issue.

**Comment by jordanjones243** [comment]
This issue has been tested in the latest version of auro-input and it is NOT VALID and this ticket will therefore be closed out.

The cursor placement still has issues and the issue to explain the bug can be found here:
- https://github.com/AlaskaAirlines/auro-input/issues/331
