### ISSUE TITLE
Pattern Attribute should throw error when string doesn't match Regex

### ISSUE THREAD

**Issue by jpalmer108** [AlaskaAirlines/auro-input#148]
## Describe the bug

As a user, when I add the pattern attribute to the auro-input component it should say the field is invalid if it doesn't match the pattern provided. 

Currently, when I attempt to pass in a Regular Expression in via variable or hardcoding the input field doesn't display any type of error when the input doesn't match the regex. 

## To Reproduce

1. Add "auro-input" component to your codebase.
2. Add "pattern" attribute to the component.
3. Type a string that should throw an error and make the field invalid.

## Expected behavior

I expected the pattern attribute to do what it says in the documentation; this means I expect the pattern attribute to throw an error if the value entered into the input doesn't match the regex. What I'm seeing instead is that no errors are being thrown, period. Correct strings pass. Incorrect strings pass. The only error I'm seeing is from the required field we also have set. 

We've attempted to get pattern to work the following ways:
- passing `new Regex("/^[a-z \'\-]*$/gi")` as a value into the component via a variable (dynamic patterns)
- hardcoding `"/^[a-z \'\-]*$/gi"` into the pattern attribute
- removing the forward and end flags = `"^[a-z \'\-]*$"` (attempting to mirror the demo)

No solutions work with the auro-input component. 

We used the online tool https://regexr.com/ to validate that our regex expression worked on all the tests we provided. The same testing passes and failures can't be recreated in auro-input.  

## Screenshots

Screen Recording can be provided, however the video is too large to attach or email. Please advise on how to link it to this ticket.  

<img width="1728" alt="Screen Shot 2022-05-18 at 4 16 04 PM" src="https://user-images.githubusercontent.com/102994201/169172922-68003bdc-fb06-4813-b9aa-ea0ae43aafd3.png">

Tried adding validateOnInput and a custom message. Still doesn't work. 
<img width="1723" alt="Screen Shot 2022-05-19 at 8 45 47 AM" src="https://user-images.githubusercontent.com/102994201/169341899-c22d1fb7-323f-4c96-858f-eecab02d760c.png">

## Desktop (please complete the following information):

 - macOS Monterey: Version 12.3
 - Chrome: Version 101.0.4951.64 (Official Build) (arm64)
 
## Additional context

Due to auro-input generally not enabling functions to determine component validation, we're blocked from enabling any type of input on our fields.

**Comment by blackfalcon** [comment]
@jpalmer108 please validate that this is your project https://github.com/Alaska-ECommerce/booking-site/blob/e92c4356b9cd9cc6ca22041d39da1ed9466a868c/package.json

If this is accurate, you are on an older version of auro-input

```
"@aurodesignsystem/auro-input": "^2.1.2",
```

The feature support you are looking for was made available with [v2.3.0](https://github.com/AlaskaAirlines/auro-input/compare/v2.2.0...v2.3.0) [Update pattern support feature #122](https://github.com/AlaskaAirlines/auro-input/issues/122)

Updating your local version should resolve the issue. If so, please close the issue once resolved.
