### ISSUE TITLE
Spacing on Amex Credit Cards is incorrect

### ISSUE THREAD

**Issue by jpalmer108** [AlaskaAirlines/auro-input#151]
## Describe the bug

As a customer, when I input my Amex credit card information into the credit cards field I expect the spacing and formatting to match what it looks like on my card. 

Instead of a 4 digit - 6 digit - 5 digit format, it is 4 digit - 5 digit - 6 digits. This just looks off as a customer, and instead of moving on with the payment process it causes pause and confusion. 

## To Reproduce

1. Go to 'auro-input' documentation at https://auro-prod-site-w2.azurewebsites.net/components/auro/input
2. Scroll down to the 'Credit Card' section
3. Click on any of the input fields shown.
4. Attempt to enter a 15 digit card number: 1111 2222 3333 444
5. See the bug. 

## Expected behavior

I expect the spacing of the digits inside of the credit card field to match what Amex has (spacing wise) on their cards. Here is a photo from google with an example of an amex card:

![image](https://user-images.githubusercontent.com/102994201/170582695-3965b1c1-886e-445e-80b7-9a7979359407.png)
Here is a screenshot of what a 15 digit string looks like in the credit card component:

<img width="485" alt="Screen Shot 2022-05-26 at 1 44 53 PM" src="https://user-images.githubusercontent.com/102994201/170582298-c02b4b15-eeb5-436a-b394-6b875088b0b8.png">

The difference is the first has the digits grouped in a 4 digit - 6 digit - 5 digit format, whereas the latter groups them in a 4 digit - 5 digit - 6 digit format. 

## Screenshots

Screenshots were provided above. Functionality of this bug is able to be viewed in auro-documentation under the credit card section when attempting to add a 15 digit string. 

## Desktop (please complete the following information):

- OS: MacOS Monterey 12.3 (21E230)
- Browser: Chrome
- Version: Version 101.0.4951.64 (Official Build) (arm64)

**Comment by blackfalcon** [comment]
AMEX cards are triggered by specific prefix numbers. When using `11111` as a leadoff you are not triggering the correct formatting. Using the number provided in the screenshot of the card, you see that the component supports the expected number formatting. 

<img width="562" alt="Screen Shot 2022-05-27 at 3 08 41 PM" src="https://user-images.githubusercontent.com/181089/170795151-49ebeec5-735f-4305-8184-4b7b954b0e0f.png">

**Comment by jpalmer108** [comment]
Great, thank you! 

I added another bug last week to add some documentation surrounding those numbers & the spacing decisions that affect them last week. It'd be great if those logical decisions on spacing were outlined clearly in the docs so I know what's working and what's not. 

Also, is the incorrect Amex spacing (4-6-5) the intended default behavior for this field if they don't enter a specific first two numbers? I might say that a group of 4 spacing would make more sense. If you could let me know @blackfalcon, that'd be great!

**Comment by blackfalcon** [comment]
@jpalmer108 so it's not so much that `4-6-5` is the 'default', but we support different credit card types by specific number sequences. 

https://github.com/AlaskaAirlines/auro-input/blob/main/src/base-input.js#L694-L777

https://wallethub.com/edu/cc/what-is-a-credit-card-number/44066
