### ISSUE TITLE
Credit Card patterns not working as expected

### ISSUE THREAD

**Issue by jpalmer108** [AlaskaAirlines/auro-input#152]
## Describe the bug

We would like to add pattern validation to the `auro-input` field when we have `type="credit-card"`. The patterns we were hoping to implement were to make sure that the user entered a full 15 or 16 digit credit card number for the field to say show it is valid. We want the field to say invalid if there is an incomplete credit card number input field. 

Currently when we attempt to add a pattern into that field it behaves very strangely. When testing with the pattern "^[0-9]{15,16}" I expected the field to say invalid until the 15th or 16th character. That was true, until you click off the field; then it would turn invalid with no explanation. When another coworker of mine was playing with it on their machine, they almost got it to work however when the field showed visibly that it was valid the isValid flag on it was still `false`, so it was very confusing. 

All in all, we've tried a number of ways to get it to work however we can't seem to get a consistent solution. 

What we desire in general is for `auro-input` with type `credit-card` to show invalid if there is an incomplete credit card string inputted. That way we can prevent purchase if they have an incomplete card. 

## To Reproduce

1. Add `auro-input` to your project with `type="credit-card"`.
2. add a pattern string to check whether or not the string is 15 or 16 digits. We used: "^[0-9]{15,16}"
3. Enter 15 or 16 characters.
4. See weird behavior (inconsistent invalid signs, false valid signs, etc.)

## Expected behavior

I expect to be able to write a simple pattern that checks whether or not there are 15 or 16 digits included as a credit card string. This is so that I can make our payment form submit button 'invalid' if any fields have missing or incorrect information. This is just with using the built in pattern attribute though. 

In general, what we desire is for the field to be able to show as invalid if an incomplete credit card string is added. We would like to add logic on other components in our repo to disable the purchase button if this field is invalid or missing. 

## Screenshots

![chrome-capture-2022-4-26](https://user-images.githubusercontent.com/102994201/170740155-2878750d-2831-49f5-8279-9c6876ecacdd.gif)

## Desktop (please complete the following information):

- OS: MacOS Monterey 12.3 (21E230)
- Browser: Chrome
- Version: Version 101.0.4951.64 (Official Build) (arm64)

## Additional context

I'm pretty sure the reason this error is being thrown is because depending on the first two digits of the credit card string inserts spaces to group specific numbered characters. However, because we don't have access to logic that shows when those different spacing patterns happen we can't adjust our pattern to match. 

That's just if you want to enforce the pattern attribute to enable this functionality. 

Something separate I noticed was that there's no explanation on the Expiration Date portion of the auro-input documentation that shows that the string renders with an actual forward slash inside. That means any numbers only pattern (ie "^[0-9]{4}" that says "expect 4 digits") to fail, because a non-digit character is forcibly put into the string. Documenting that you have to be aware of this backslash character would be helpful for future users of this field. Our new pattern that works with this component is: "^[0-9][0-9]/[0-9][0-9]". This gets us what we need so far.

**Comment by jpalmer108** [comment]
Just an FYI, we are currently blocked from developing a feature on our microsite by this bug: https://dev.azure.com/itsals/E_Sell_Book/_backlogs/backlog/E_Sell_Book%20Team/Features/?workitem=757702

**Comment by blackfalcon** [comment]
@jpalmer108 a few things I want to comment on here. I do not 100% understand why you are setting up a custom pattern for the credit card? What is the use case that you need to address? With each credit card type we are supporting, we pre-define the min and max length of characters and set up the pattern. The pattern you are trying to eval we already support. 

https://github.com/AlaskaAirlines/auro-input/blob/main/src/base-input.js#L671-L687

Testing with a card number that starts with `1` is most likely causing you some issues. The input element credit card type uses https://nosir.github.io/cleave.js/ as the UI logic. We feed specs into the cleave API and it renders the UI spacing. 

> However, because we don't have access to logic that shows

The functionality for the feature is in this repo https://github.com/AlaskaAirlines/auro-input/blob/main/src/base-input.js#L694-L777 and all other logic is dependent on cleave.js

The same is true for the date input. Please see lines https://github.com/AlaskaAirlines/auro-input/blob/main/src/base-input.js#L216-L270 for how we set up the cleave.js API here as well.
