### ISSUE TITLE
Calendar icon moving when it should stay put.

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-input#155]
## Describe the bug

- The calendar icon is moving when the field become active but the icon should stay put

## To Reproduce

1. Go to '[The date examples](https://auro.alaskaair.com/components/auro/input#:~:text=Use%20the%20type%3D%22month%2Dday%2Dyear%22)'
1. If you zoom in you'll see the white text behind the grey placeholder text.

## Expected behavior

No text visible

## Screenshots

![image](https://user-images.githubusercontent.com/5118118/170777251-46334c2b-e36d-4dca-9e01-06d580ee635d.png)

**Comment by blackfalcon** [comment]
@braven112 the issue title says one thing and the description says another. I am assuming that you are raising an issue about the placeholder text, but I want to make sure.

**Comment by blackfalcon** [comment]
Just checked the Auro site and this issue appears to be resolved. Cleaning house and closing this issue.
