### ISSUE TITLE
Input & Validation Events Race Condition

### ISSUE THREAD

**Issue by jpalmer108** [AlaskaAirlines/auro-input#156]
## Describe the bug

My team is currently working on creating a form with a number of different fields and validation types. We want all fields who fail our validation (and requirement standards) to perform logic that disables the 'purchase' button as well as other visual notifiers that the data is incorrect. 

We are currently working in a React Application, so the encouraged way to get both the `input` and `isValid` data is via events; in this case the `input` event and the `auroInput-validated` event. These two events fire simultaneously when input is added to the `auro-input` component. 

Our issue is that given the way these events were given to us, they currently encourage the development of a race condition that is pretty difficult to resolve. 

We store our fields in a single object with two attributes (example below);
```javascript
// example object
const fieldData = {
  value: 'test',
  isValid: true
}
```

When the `input` event listener is triggered, it updates the `value` property of that object. 
When the `auroInput-validated` event listener is triggered, it updates the `isValid` property of that object. 

Because both events fire simultaneously, they overwrite each other, leaving one of the two values missing (whichever event fired second). In general, there really isn't a way for us to get around this without storing data in two separate locations, however that's really bad practice as those two attributes should be connected because they are functionally connected. 

We've been able to get around this for now because the input field just returns the entire `Input Event` that is triggered from this event. This `Input Event` contains the element itself that was being triggered, meaning we're able to actually grab the isValid property that is currently set on that element. 

```javascript
// added event listener for auro-input 'input' event

// example of how we get around it (event => `Input Event` object received from 'input' event)
const fieldData = {
  value: event.target.data,
  isValid: event.target.isValid
}
```

All in all, I'd suggest that the "auroInput-Validated" event is removed and combined with the "input" event as to avoid the race condition. That way we can keep with best data storage practices and avoid two events triggering at the same time. 

## To Reproduce

1. Add 'auro-input' component to your project. 
2. Add 'input' event listener to that component, and `console.log` result. 
3. Add 'auroInput-validated' event listener to that component, and `console.log` result. 
4. Run project.
5. Enter Input into rendered field.
6. See two events fire at the same time; notice how storing both data points (input string, and isValid boolean) would be difficult to store in the same location. 

## Expected behavior

In general, I expect `auro-input` to be able to provide me with an easy way to grab the newly input data into the field as well as alerting me to whether or not it passes or fails my validity check; essentially returning two data points (value, isValid) on input trigger. 

While technically I'm able to do this today, the documentation suggests that I should be doing this with two different events that fire simultaneously. 

I'd appreciate either:
- Auro's event docs to say say you can get both the input & isValid data points from one event
- Combining both "input" and "auroInput-validated" into one function and explaining you can get both there

Either way, the way the api docs are now almost encourages a race condition. 

### Result from "input" event: 
<img width="1305" alt="Screen Shot 2022-05-31 at 3 08 16 PM" src="https://user-images.githubusercontent.com/102994201/171295676-0c36a749-ca5d-465b-8ed3-14aa373dc413.png">

Find important data at: 
- **value**: event.target.value
- **isValid**: event.target.isValid

>Note: The 'Type Returned' portion of this event's API doc is wrong. The docs don't outline what is returned but it is an entire Input Event object. I'm attempting to update that object in the API docs currently. 

### Result from "auroInput-validated" event:
<img width="1302" alt="Screen Shot 2022-05-31 at 3 07 44 PM" src="https://user-images.githubusercontent.com/102994201/171295622-03c06623-bb8f-4290-a74d-ca36caddef0f.png">

Find important data at: 
- **isValid**: event.details.isValid

>Note: The 'Type Returned' portion of this event's API doc is wrong. It is not `CustomEvent<{isValid: boolean>`, it is an entire Custom Event object. I'm attempting to update that object in the API docs currently. 

## Desktop (please complete the following information):

- OS: MacOS Monterey 12.3 (21E230)
- Browser: Chrome
- Version: Version 101.0.4951.64 (Official Build) (arm64)

## Additional context

I'm currently in the process of updating the documentation to reflect what is currently live. 

Also note, because we're able to get around the bug by utilizing the `input` event's response we will have to update our application should changes be made to that event's response.

We realize our solution felt a little "tech debt-y" and only felt comfortable releasing to prod if we actually created an issue for the debt we were seeing. This is why we made the Github issue even if we've gotten around the problem.

**Comment by jpalmer108** [comment]
Created the PR above to address the API doc inconsistencies with what's currently deployed. This pull request DOES NOT address the issue brought up in this issue.

**Comment by blackfalcon** [comment]
The API document you updated is not a static document. With each build this is auto-generated from the code. For example, please see https://github.com/AlaskaAirlines/auro-input/blob/main/src/base-input.js#L465-L472 as the lines that generate the update you edited for `auroInput-validated`. 

Please see [this README](https://github.com/runem/web-component-analyzer/blob/master/README.md#-how-to-document-your-components-using-jsdoc) for how to use JSDoc with web components.

**Comment by jpalmer108** [comment]
> The API document you updated is not a static document. With each build this is auto-generated from the code. For example, please see https://github.com/AlaskaAirlines/auro-input/blob/main/src/base-input.js#L465-L472 as the lines that generate the update you edited for `auroInput-validated`.
> 
> Please see [this README](https://github.com/runem/web-component-analyzer/blob/master/README.md#-how-to-document-your-components-using-jsdoc) for how to use JSDoc with web components.

I might need some assistance figuring out how to update the docs then. If its programmatically created, I don't know how to get what makes sense in there. The way the docs show Event Type make me thing calling "auroInput-validated" would get response like this `Custom Event { isValid: true }`, but that's not what we see. How can I make a more detailed response to illustrate you get a full element with the `isValid` attribute in the `event.details` section?

The same goes for the input event. How do I outline that a full `Input Event` is added, as well as the updated description? 

Apologies in advance, this is my first `auro-input` PR.

**Comment by jpalmer108** [comment]
If updating this doc requires making implementation changes to the codebase, I'm inclined to delete the PR because I'm not familiar enough with its internal mechanics to enable it to generate the documentation that would be easier for users to understand.

Would love your advice on next steps, @blackfalcon. Thanks!

**Comment by MattSidor** [comment]
We're using `<auro-input>` in production with React currently, and we are able to capture changes to both `event.target.value` and `event.target.isValid` properties in a single event, passed via a function we set on the `onInput`, `onBlur`, and `onFocus` event attributes. You shouldn't need an additional event listener for `auroInput-validated`.

Here is an example on CodeSandbox: https://codesandbox.io/s/auro-input-in-react-example-2trqfu

I think this is how you already handled it in your "workaround" example, and I think this is the intended way to capture both properties. `auroInput-validated` should only be used if you are solely concerned with `isValid`.

**Comment by MattSidor** [comment]
Sorry, I just noticed you are using `event.target.data` instead of `event.target.value`; that could also be causing an issue here?

**Comment by jpalmer108** [comment]
@MattSidor In regards to your latest comment, I think that was just a mistype on my end. 

But the previous comment makes sense! Is there a way to update the docs to where that is called out? I keep running into this issue where I look to the docs for ways to get the data I need and am a tad dumbfounded when reading; when I finally get something to work it feels 'hacky' because I'm usually not using the event (or other feature) the way the documentation alongside that event says it should be used. 

Is there a way to better update that documentation so that others don't have to go through everything I went through to get that isValid data point? I'm at a loss for how to do that considering the api readme is auto-generated. 

I'm really just trying to prevent others from going through everything we went through when trying to add validation. It took us nearly a day and a half to figure out we could get that isValid data from the "input" event because we were trying to use the docs "validated" event and having an issue updating that single object.

**Comment by jpalmer108** [comment]
Awesome thank you so much for your response. 

I'd love to see a short code snippit demo this functionality just so that getting the isValid field is shown. I'm familiar with events on getting `event.target.value`, I just didn't expect the `isValid` attribute to be accessible there since I didn't see that it should be (or could be) accessible there via the docs. I'll make that update in my PR and hopefully make the docs more clear. 

Thanks for your offer to connect with me also! I'll definitely be taking you up on that next time we come into an issue. If there's anything I can do to better communicate the issues we're experiencing, please don't hesitate to give me feedback! I'm trying to be as researched and communicative as possible when making Github issues, so if I'm forgetting to do something (or you have a new pattern you want me to follow) please let me know. 

Thanks again! Be on the lookout for an updated PR.

**Comment by jpalmer108** [comment]
I was wondering though, @blackfalcon, why is there an "auroInput-validate" event if the "input" event gives both string and "isValid"?

**Comment by jason-capsule42** [comment]
> I was wondering though, @blackfalcon, why is there an "auroInput-validate" event if the "input" event gives both string and "isValid"?

`auroInput-validate` is used for cross component communication of error states in more complex multi-tiered Auro components such as `auro-combobox` where the validation state needed to be kept in sync between the various peer dependencies (e.g. dropdown and input). In this specific case, it was better to rely directly on a validation state change event than to watch for an input value change and look for the resulting validating check that came with it.

**Comment by jpalmer108** [comment]
@jason-capsule42 That makes a lot of sense, thank you for responding! I might add something like that to the event description, just to make it more clear in my PR. Really appreciate the camaraderie while we're trying to figure this out. Cheers!
