### ISSUE TITLE
Allow function to determine `isValid`

### ISSUE THREAD

**Issue by jpalmer108** [AlaskaAirlines/auro-input#160]
## Is your feature request related to a problem? Please describe.

Our team has a **date of birth** input field we require our passengers to fill out before submitting their ticket booking. We need a better way to set input validation on this field because a regex pattern won't evaluate whether or not the date is in the future, or if there's a 31st date on that month. 

## Describe the solution you'd like

We would like a way to pass in a function that allows us to determine whether or not the field is inValid. This way we ourselves can check whether or not our string isn't within the bounds we need it to be. 

Example:
Pattern we currently use: 
`pattern="^(0[1-9]|1[0-2])/([0-2][0-9]|3[0-1])/(([1][9]|[2][0])[0-9][0-9])$"`

| Date | Our Pattern Result | Our Desired Result | Reason |
| --- | --- | --- | --- |
| 12/1/2021 | Pass | Pass | Valid string |
| 1/1/1400 | Fail | Fail | No one from before 1904 is currently alive |
| 2/31/2021 | Pass | Fail | No 31st in Feb |
| 1/1/2456 | Pass | Fail | This date hasn't happened yet |

## Describe alternatives you've considered

We've attempted to write our own regex pattern, however it doesn't allow us to dynamically check whether or not the string is considered a future date from today. 

## Additional context

Our live demo site where that pattern logic will be live by Monday: https://booking-site.ecomm-test-aks.alaskaair.com/

**Comment by blackfalcon** [comment]
@jpalmer108 I feel like you may be overthinking the pattern. aur0o-input with the `type="month-day-year"` attribute already address a few things. Like, I am curious as to how you are able to get `2/31/2021` to pass? Looking at the Auro site and your linked demo, when I type on `231` it auto-updates to `2/29`.

For things like `1/1/1400` yes, you would be responsible for creating a validation of data for that. The responsibility of this element is to format correct dates, but not to guard against specific ranges. 

So really, your regex would only be concerned about the last 4 digits. Maybe your regex would be something like 

```
\d\d\/\d\d\/(1[9]\d\d|2[0]\d\d)`
```

Or a simple function like 

```
const value = `1/1/2024`

const year = value.split("/").pop();
valid = year >= 1900 && year <= 2022
```

**Comment by jpalmer108** [comment]
> You should be able to achieve what you are looking for by writing your function to calculate the date restrictions described and then applying the desired string to the error attribute.

Where is this documented? I look in the api and that attribute doesn't say anything about allowing us to pass in a function?

And @blackfalcon you're probably right about us over-thinking the regex. If we knew there was a way to do validate via function, we would have done that instead. We're regex novices hahaha

**Comment by jpalmer108** [comment]
I think I understand what error is doing after playing with it. We can pass in a string to show an error, and only make the string get returned if it fits our guidelines. I can add a section to the docs that cover this.

**Comment by jason-capsule42** [comment]
> Where is this documented? I look in the api and that attribute doesn't say anything about allowing us to pass in a function? And if we're able to pass in a function that returns a string, why is it a string that evaluates whether or not its in error state and not a boolean?

I think the error support section of the demo page covers this pretty well. What additional content changes are you thinking?

**Comment by jpalmer108** [comment]
> I think the error support section of the demo page covers this pretty well. What additional content changes are you thinking?

I added a PR request above, let me know what you think. Even this one line would have significantly increased my understanding of the app's capabilities and functionality when searching through the docs.
