### ISSUE TITLE
input date validation 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-input#164]
## Is your feature request related to a problem? Please describe.

The current implementation for input type date validates with any character entered. This is baseline validation. The field has a value. The gif below illustrates that simply putting in a `1` the element will consider this field `valid`. 

![issue](https://user-images.githubusercontent.com/181089/171951401-e3736d7d-5a54-4404-b9b3-16841dc20fe7.gif)

## Describe the solution you'd like

The validation should be smarter so that when a date type is selected, that is the value it should validate on. 

For example, if `type="month-day-year"` is used for auro-input, the validation should be looking for `MM/DD/YYYY`.

**Comment by jason-capsule42** [comment]
<img width="1055" alt="Screenshot 2023-03-20 at 8 05 31 AM" src="https://user-images.githubusercontent.com/23223137/226381879-6fecacb1-e8f9-4349-897f-a3a374f5a9ce.png">

Seems like the existing validation is already doing what it is supposed to do here.
