### ISSUE TITLE
Decompose auro-input into smaller individual elements RFC

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-input#165]
## Is your feature request related to a problem? Please describe.

Auro Input is too big. There are way too many concerns in this one element. The complexity of features increases the risk of updates. It's too easy to break things. 

## Describe the solution you'd like

The `auro-input` could be broken down into the following individual elements. 

1. auro-input only supports common types. `text`, `email`, and `password`. 
1. auro-input to support common states. `disabled` and `error`. 
1. auro-creditcard to support all current credit card features and icons with cleave.js dependency 
1. auro-inputnumbers to support our custom input of `type="number"` with cleave.js dependency 
1. auro-inputdate to support our custom date input types with cleave.js dependency 

There are two ways we can do this. One is to make each sub-component an individual repo or we could make this a mini mono-repo for input elements. 

Due to the cleave.js dependency, I am more drawn to having these as a suite of input elements, versus multiple repos. 

Additional context: if we are to support a mini mono-repo, we need to have a better solution for importing each element. E.g. it's just lame that we have pointers going deep into the `./dist` directory when accessing alternate elements in a single repo.

**Comment by blackfalcon** [comment]
@MattSidor @geoffrich @jason-capsule42 this issue is a [RFC](https://blog.pragmaticengineer.com/scaling-engineering-teams-via-writing-things-down-rfcs/). I am interested in feedback prior to jumping in and executing on this one.

**Comment by blackfalcon** [comment]
It appears that we may need auro-inputphone as well? 

- https://github.com/AlaskaAirlines/auro-input/issues/78

**Comment by MattSidor** [comment]
I was actually just thinking earlier this week that it would be nice to have a simpler, "stripped-down" version of auro-input without the validation features. This seems like a good idea to me.

**Comment by blackfalcon** [comment]
> I was actually just thinking earlier this week that it would be nice to have a simpler, "stripped-down" version of auro-input without the validation features. This seems like a good idea to me.

This isn't crazy. We'd have to rethink what the baseline element is so that we can extend into each of these individual use cases. 

I really don't want to get into having each version be a wrapper around a baseline. If we can extend, then we don't have to get into custom event hell. 

So, based on this, I guess I am also advocating for a suite of elements versus individual repos.
