### ISSUE TITLE
Clicking anywhere in datepicker auto puts user cursor at end of date

### ISSUE THREAD

**Issue by bridgetglewis** [AlaskaAirlines/auro-input#172]
## Describe the bug

No matter where in the datepicker input field a user clicks, they will automatically be sent to the end when they use the keyboard functions, causing incorrect adjustments to datepicker. We want the input functions/cursor to remain where the user originally clicks.

## To Reproduce

1. Go to '[alaskaair.com/search-test/](https://www.alaskaair.com/search-test/)'
2. Click into the day region of the date within auro-datepicker (either within 'Departing' or 'Returning')
3. Delete once and type any number (i.e. today's date is 08/16/2022; click between 1 and 6 of 16, delete the 1 and type 2, as if the 

## Expected behavior

The expected behavior would be for the input to take information from where the user originally clicks. In the example above, the date would change from 08/16/2022 to 08/26/2022 when the user clicks between the 1 and 6, deletes, and types '2'.

## Screenshots

1. Current date is 08/16/2022 
![Screen Shot 2022-08-16 at 3 10 27 PM](https://user-images.githubusercontent.com/50185074/184994205-001ff12f-6d52-47ca-b5df-46567411e96d.png)
2. User clicks in between 1 and 6 of 16 
![Screen Shot 2022-08-16 at 3 10 40 PM](https://user-images.githubusercontent.com/50185074/184994253-38ba70af-6f96-45ff-9e74-e78a6c77079f.png)

3. User deletes the '1' 
![Screen Shot 2022-08-16 at 3 10 56 PM](https://user-images.githubusercontent.com/50185074/184994362-dff3d2ff-5006-40d2-9967-859051275988.png)

4. User types '2' as if to change the date to 08/ '2' 6/2022 
![Screen Shot 2022-08-16 at 3 11 02 PM](https://user-images.githubusercontent.com/50185074/184994386-23fbc83d-a7f6-448d-b5c7-2578bffba5e4.png)

## Desktop (please complete the following information):

 - OS: iOS
 - Browser: Chrome
 - Version: ??

**Comment by erikalanghauser** [comment]
@braven112 @blackfalcon any update on this issue as we approach our flight search launch date?

**Comment by blackfalcon** [comment]
This was added to a list of issues that Diana gave us to review and give feedback on last Friday. We are in the process of reviewing priorities and planning upcoming sprints.

**Comment by jordanjones243** [comment]
This ticket is a two part problem and is split up into these two tickets:
https://github.com/AlaskaAirlines/auro-input/issues/181
https://github.com/AlaskaAirlines/auro-input/issues/182
