### ISSUE TITLE
"Please fill out this field" text overrides the helpText slot value when the required flag is passed

### ISSUE THREAD

**Issue by shonore-aa** [AlaskaAirlines/auro-input#175]
## Describe the bug

If the "required" property is passed to the component and the component is put in error state the text "Please fill out this field." populates the helpText regardless of what value is passed to the helpText slot

## To Reproduce

1. Pass the "required" property to the auro-datepicker
2. Set the helpText slot value to any error message string
3. Add logic to have the datepicker go into the error state when the date is in the past
4. Select the auro datepicker and type in a past date that will cause the datepicker component to error
5.  The datepicker will go into error state but it will show the text "Please fill out this field"

## Expected behavior

The datepicker should show the text value passed to the helpText slot

## Screenshots

![Screen Shot 2022-08-19 at 11 01 50 AM](https://user-images.githubusercontent.com/107429014/185660410-db930708-1687-413d-9514-3f52292a91d1.png)

![Screen Shot 2022-08-19 at 11 02 13 AM](https://user-images.githubusercontent.com/107429014/185660440-990ab157-ace4-4219-8ea1-4959bbbcdfaa.png)

## Desktop (please complete the following information):

 - OS: MacOS
 - Browser: Chrome
 - Version: latest

**Comment by braven112** [comment]
This one is similar to #170  but in this issue the text "Please fill out this field." is overriding the value passed to the helpText slot.

**Comment by isaiahscheel** [comment]
Any updated on this @braven112 ?

**Comment by blackfalcon** [comment]
@isaiahscheel this issue sparked some team discussions that resulted in a solution for this and additional work. I will be touching base with @jason-capsule42 as to the status of stories we need to create to address this and other similar issues.

**Comment by blackfalcon** [comment]
There is a validated error with this element and the `required` state. Testing locally with the repo demo, when I place the `required` attribute on the auro-datepicker element, the element's value is `undefined` and triggers an error state. 

It's also validated that, when the `required` attr is used, selecting a date from the popout calendar is not operating as expected either. 

But when a valid date is typed into the element, this appears to work as expected. 

> The datepicker should show the text value passed to the helpText slot

That is not a correct statement. The default behavior is; when help text is entered into the UI via a slot. When there is an error, this overrides the help text and replaces it with the error message. Once the error is clear, the help text will return. 

If there is a desire to have the value of the input be represented into the help text slot, that would be up to the using engineer to replace the content in that slot with the value from the element. 

I added the `not-reviewed` label back to this element to spark a discussion with the rest of the team.

**Comment by shonore-aa** [comment]
@blackfalcon We are seeing this behavior with the latest version of the auro-datepicker (v1.2.2).
