### ISSUE TITLE
Setting value = undefined does not reset the value of the html5 input

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-input#191]
## Describe the bug

When resetting the value of the auro-input the html5 input in the shadow DOM does not reset it's value.

## To Reproduce

1. Setup an input with a value in it
2. call `auro-input.value = undefined`
3. Check the displayed value of the html5 input in the shadow DOM

## Expected behavior

The html5 input element should not have a value

**Comment by DZwell** [comment]
I'm also able to repro this. Check the screen shot below:

![image](https://user-images.githubusercontent.com/10947475/193892992-7b8c1bb4-0346-44b5-91aa-09fbcf37f25a.png)


This is after I set the value of the `auro-input` to `undefined`. You can see on the right side in dev tools that both the text content and value of `auro-input` are empty string and `undefined` respectively. The underlying `input` field in the `shadowRoot`, however, retained the value.
