### ISSUE TITLE
ods-inputtext does not fire event when you click X to clear the field

### ISSUE THREAD

**Issue by liambrozik** [AlaskaAirlines/auro-input#2]
## Steps to reproduce
If you attach an `input` event listener to the component and then type in the text field, you will see that events are fired. If you click the 'X' to clear the field, you will see that an event is not fired. 

## Expected behavior
If one presses the 'X' to clear the text field, the component should dispatch an input event. Without this event, there is no way for a consumer of the component to tell that the 'X' was pressed.

**Comment by blackfalcon** [comment]
Update: See running version of this option at http://auro-22.surge.sh/

@liambrozik please let me know if this is the solution you are looking for.

**Comment by liambrozik** [comment]
Per the [CustomEvent() spec](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent), it looks like the `'clearElement'` event you defined should work. 

On the auro-22.surge.sh site I added an ID to the first Input component and then added an event listener like this:
`document.querySelector("#testingInput").addEventListener("clearElement", e => console.log(e.type == "clearElement"));`

It does not seem to be firing? Maybe I am doing something wrong on my end...

**Comment by blackfalcon** [comment]
A more effective way to test this would be to clone down the repo, `npm i && npm run ciBuild && npm link` 

Then link the npm to your project, `npm link @alaskaairux/auro-input`

You should be able to test the component in your project with more stability.
