### ISSUE TITLE
Text only ellipses when something else on document is given focus

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-input#202]
## Describe the bug

When clicking on something else within the window, but outside of the document, the text does not ellipse.

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/input in Google Chrome
1. Open dev tools
1. Give focus on default bordered example
1. Type in a long list of characters that exceeds the width of the input
2. Click into dev tools
3. See error
4. Click back onto document, but not into the bordered auro-input default example
5. See correct behavior

## Expected behavior

auro-input text should ellipse is not in focus at any given time.

**Comment by jason-capsule42** [comment]
We discussed this issue during refinement and this is expected behavior. Browser clients do not fire a focusOut event when switching windows which prevents our UI from taking any action tied to that event.
