### ISSUE TITLE
Padding of label input does not take icon attribute into account

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-input#203]
## Describe the bug

The label text exceeds the `auro-input` width when there is an icon attribute is present and there is an icon to the left of the HTML5 input inside of `auro-input`.

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/input#gsc.tab=0 on Google Chrome
2. Open dev tools
1. Scroll down to Credit Card example with `auro-icon`
3. Input a full credit card number
4. Change width of window to 167px.
1. See error

## Expected behavior

Label text should fit inside of the `auro-input`, no matter the width.

## Screenshots

![Screen Shot 2022-10-12 at 1 04 45 PM](https://user-images.githubusercontent.com/55807669/195437286-e2ce1a43-2e06-4a2c-ba6b-b238daaf7129.png)

**Comment by blackfalcon** [comment]
Please consult with @leeejune about where the icon should be with the input without a border and no value. Design is to instruct dev what the next steps are. Please add decisions to this issue going forward.

**Comment by blackfalcon** [comment]
The issue related to the ellipsis is NOT an issue to be addressed at this time.
