### ISSUE TITLE
type="number" not working since 2.10.0

### ISSUE THREAD

**Issue by jordanchang** [AlaskaAirlines/auro-input#209]
## Describe the bug

Since v2.10.0, the type="number" attribute is not working as designed.

## To Reproduce
1. Copy the example Number input from Auro Docs:

```
<auro-input required type="number" id="demo40" maxlength="12">
  <slot slot="label">Account number</slot>
  <slot slot="helptext">Please enter your 12 digit account number.</slot>
</auro-input>
```

## Expected behavior

User should not be able to enter alpha

## Screenshots

![image](https://user-images.githubusercontent.com/3304352/198115321-c577a400-ee03-435b-a34d-1f9e0f186a37.png)

## Desktop (please complete the following information):

Repro-ed on Desktop

**Comment by blackfalcon** [comment]
@jordanchang I am unable to repro this issue on the [auro docsite](https://auro.alaskaair.com/components/auro/input) and this is using the latest 2.10.1. 

Can you verify?

**Comment by jordanchang** [comment]
This is weird. I deleted node_modules and package-lock and its working now. Uggs. Apologies and closing.
