### ISSUE TITLE
Error state border thickness changes at breakpoint

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-input#212]
## Describe the bug

The error state border changes thickness from 2px to 1px at the 660px breakpoint.

## To Reproduce

1. Go to [https://auro.alaskaair.com/components/auro/input#gsc.tab=0](https://auro.alaskaair.com/components/auro/input)
2. Inspect on Chrome
3. Change the width of the screen to 659px.

## Expected behavior

The error state border should always be 2px.

## Screenshots
![Screen Shot 2022-10-31 at 12 05 34 PM](https://user-images.githubusercontent.com/55998746/199093239-6152b896-a917-430d-9455-f209dc3a2bf2.png)
![Screen Shot 2022-10-31 at 12 05 14 PM](https://user-images.githubusercontent.com/55998746/199093243-02f565a2-9b15-4bac-9aac-338de40941d8.png)

## Desktop (please complete the following information):

 - OS: [e.g. iOS] macOS
 - Browser: Chrome
 - Version: Version 106.0.5249.119

**Comment by Patrick-Daly-AA** [comment]
Verify this in Beta branch to see if this has been fixed.

**Comment by jordanjones243** [comment]
This issue is no longer a bug. Border appears as 2px both in mobile and desktop versions. This ticket is now closed.
