### ISSUE TITLE
Setting value=undefined does not reset validation state

### ISSUE THREAD

**Issue by jordanchang** [AlaskaAirlines/auro-input#213]
## Describe the bug
As a developer, I want to allow users the ability to clear an auro-input. Clear should remove any text that was entered and reset validation state.

1. Add an auro-input with a regex pattern to webpage. For example, an auro input for the 6 letter confirmation Code:

```
     <auro-input bordered validateOnInput requestparam="confirmationCode" label="Confirmation code" pattern="[A-Za-z]{6}">
            <span slot="helptext">May only contain letters. Length of 6 characters.</span>
     </auro-input>
```
2. Type in something invalid.
3. Via javascript set the value to undefined to "clear" the value of auro-input.
4. Auro-input value is cleared but the validation error decoration is still present

![image](https://user-images.githubusercontent.com/3304352/199627633-88b6f7fc-7fb2-47bd-9888-27a440de8be7.png)

## Expected behavior

Clear should remove any text that was entered and reset validation state.

## Additional context

This might not be a bug, but I just need guidance on how to clear auro-inputs.

**Comment by blackfalcon** [comment]
So the issue is regarding the regex you used. Once you interact with an element it now has state. The value of the input will always eval against the value of the regex. If that value does not match, e.g. undefined, that is invalid and the error state will appear to the user. 

So, this is working as expected.

**Comment by jordanchang** [comment]
Thank you for the explanation. We ended up clearing the field using empty string and that kept the validator happy.
```
myelement.value = '';
```
