### ISSUE TITLE
Input field should not run validation when disabled

### ISSUE THREAD

**Issue by DZwell** [AlaskaAirlines/auro-input#220]
## Describe the bug
We have a disabled credit card input where we only display the last four digits of the CC number which renders the credit-card type input as invalid. Since the input value is not valid, auro-input complains. Since the field is disabled, you can't fix the problem.

## To Reproduce
1. Set input as disabled
2. Hard code it with an invalid value

## Expected behavior
Auro input should ignore validation when disabled.

## Screenshots
![image](https://user-images.githubusercontent.com/10947475/201194495-7858b6ff-2c2a-424d-b6d3-d59b1501f246.png)

## Desktop (please complete the following information):

 - Browser [Firefox and Chrome]

**Comment by blackfalcon** [comment]
Plauseable issue is related to users setting up a scenario that we are not fully supporting. Is the user preloading the a value into the input and we are running validation at the same time causing an error in the flow. 

There is an idea that regardless of content/value in the input, if the input is `disabled` the error logic should not run. 

Would the `no-validate` attr support this situation? 

@blackfalcon is to follow up with @DZwell as to the current status of this UI in their app and recommend a solution going forward.

**Comment by blackfalcon** [comment]
We need to discuss a new feature with auro-input credit card support to support a `last four` number scenario as a valid input.

**Comment by blackfalcon** [comment]
@DZwell is currently on PTO, we will come back to this issue upon his return.

**Comment by Patrick-Daly-AA** [comment]
We've made some significant updates to input validation across all our components and believe this has been fixed.  Will need to validate.

**Comment by blackfalcon** [comment]
Validated, no longer an issue.
