### ISSUE TITLE
Add autocomplete attribute to API

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-input#23]
## Is your feature request related to a problem? Please describe.
As a user, I want to have auto-completion when using an auro-input, so that I can fill in forms faster.

## Describe the solution you'd like
We should expose [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) as part of the API and directly set it on the shadow input.

It should support all the values the normal autocomplete does -- I don't think we should be only allowing a subset. auro-input is used in many different contexts.

## Describe alternatives you've considered
Set it in the component based on the type of input. As mentioned above, I don't think this makes sense. The consumer of the component might want to set "given-name" on one input and "family-name" on another.

## Additional context
We should verify this works on a mobile browser and doesn't run into any issues with the shadow DOM.

We should also see how this affects credit card formatting. We might need to listen to an event to detect when a field has been autofilled and reformat the input.

**Comment by geoffrich** [comment]
In regards to shadow DOM, this part of the MDN docs worries me:

> In order to provide autocompletion, user-agents might require <input>/<select>/<textarea> elements to:
> 
> 1. Have a name and/or id attribute
> 2. Be descendants of a <form> element
> 3. The form to have a submit button

inputs in the shadow DOM might fail point 2.

**Comment by blackfalcon** [comment]
@geoffrich this is coming. Thanks for the issue. The plan is to pair this with auro-dropdown and the auro-menu CEs that are currently being developed with auroLabs. 

Is there an upcoming 'need' you need to address?

**Comment by geoffrich** [comment]
Not related to an upcoming need, but a nice-to-have. Note that this is distinct from an auto-populated dropdown with airport codes or something, which I think is what menu/dropdown is intended to address. This is the native browser autocomplete that will suggest stored data for form fields depending on the attribute. For instance, if I have the text field `<input type="text" autocomplete="name">`, my phone would suggest "Geoff Rich" for that field (same with addresses, stored credit cards, phone, etc). There is not currently a way to do that with auro-input. I want to be able to do something like `<auro-input autocomplete="name">` and have the attribute propagated down to the shadow input.

See the [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) reference.

**Comment by blackfalcon** [comment]
Ohhhh, I see where you are going with this. Yeah, I don't see why we can't support this. We already fully support the main criteria 

```html
<div>
  <label for="cc-number">Enter your credit card number</label>
  <input name="cc-number" id="cc-number" autocomplete="off">
</div>
```

I see no reason why not to support this. The work is minimal, we just need to allow the attribute. The native browser API would take care of the rest I imagine.

**Comment by blackfalcon** [comment]
This also needs to get renamed

https://github.com/AlaskaAirlines/auro-input/issues/22

**Comment by jason-capsule42** [comment]
Shadow DOM prevents us from doing a proper implementation of the `autocomplete` attribute on the input here. The clients are not able to properly inject their stored values to inputs nested inside the shadow DOM.

@geoffrich I am kicking this one back over to you. If you have any ideas on another approach please comment. Otherwise, I suggest we close this issue out.

**Comment by geoffrich** [comment]
I want to try a couple things out before closing the issue. I'll report back soon.

**Comment by blackfalcon** [comment]
@geoffrich did you have anything else to report on this? Would you still consider this `in progress`?

**Comment by geoffrich** [comment]
This [Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=649162#c28) I found a few days ago leads me to believe that this should be possible, or at the least is a bug they want to fix. So I think `autocomplete` is still something we should add the API at some point. Whether we want to just add it before Chrome ships a fix or if we want to verify that it actually works before adding it is up for discussion.

I wouldn't consider it "in progress" at the moment, though, since I'm not actively investigating.

**Comment by blackfalcon** [comment]
Another team reached out to ask about this feature. I don't remember exactly where we left off, there at not any notes to job full memory.

To get this conversation started again, I created a `draft PR` to review and there is a demo here https://input-autocomplete-23.surge.sh/

**Comment by blackfalcon** [comment]
I also just discovered that there is an issue with passwords and the shadow DOM, this is captured in this issue with WebKit https://bugs.webkit.org/show_bug.cgi?id=203299 and brought to Justin's attention [a few months back](https://githubmemory.com/repo/WICG/webcomponents/issues/926).

Having gone through this, I am seeing where we can offer limited functionality for this feature, but we need to be clear as to what we DO and DO NOT support with this element and why.

**Comment by geoffrich** [comment]
>Having gone through this, I am seeing where we can offer limited functionality for this feature, but we need to be clear as to what we DO and DO NOT support with this element and why.

Yeah, I'm in favor of exposing the autocomplete attribute entirely (as your PR did) and add a disclaimer to the attribute that it may not work in all browsers.

It would be nice to confirm it works in at least _some_ browser before adding the attribute, though.

**Comment by blackfalcon** [comment]
The reality of it is, this is one of the most inconsistently enabled browser features. For the most part, most of the documentation is about how to disable this feature. 

Using the same form, that I did not develop, that exhibits this feature, it works in Chrome. Does not work in Firefox and of course, Safari has its own twist on it. 

So yes, I don't see an issue with enabling this feature, but with the huge caveat that this feature is a mess and we are not responsible for inconsistent browser scenarios. 

<img width="475" alt="Screen Shot 2021-11-17 at 10 27 05 PM" src="https://user-images.githubusercontent.com/181089/142363829-b7e3f04e-08e2-43ed-8521-9571b706ec30.png">

**Comment by blackfalcon** [comment]
Work carried forward in https://github.com/AlaskaAirlines/auro-input/issues/84
