### ISSUE TITLE
Missing updates for Node 18+ support 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-input#254]
# General Support Request

The following issues were found in the recent PR to be corrected. 

## Support request

**Related to issue #251**

```
npm WARN deprecated @alaskaairux/webcorestylesheets@3.7.3: Web core stylesheets with the @alaskaairux namespace is no longer supported. Please update to the new @aurodesignsystem/webcorestylesheets @4.0 to be current with all new changes
```

**Related to issue #248**

1. Delete  ./index.html 
2. Delete ./src/style-fixed.scss
3. Delete ./scripts/removeNonRemPlugin.js

Remove these lines

https://github.com/AlaskaAirlines/auro-input/blob/443a6e02040cbb77b63499d4ff47e4b7f8f873b3/package.json#L95

https://github.com/AlaskaAirlines/auro-input/blob/443a6e02040cbb77b63499d4ff47e4b7f8f873b3/package.json#L30

https://github.com/AlaskaAirlines/auro-input/blob/443a6e02040cbb77b63499d4ff47e4b7f8f873b3/package.json#L66-L69

https://github.com/AlaskaAirlines/auro-input/blob/443a6e02040cbb77b63499d4ff47e4b7f8f873b3/package.json#L146

**Related to issue #249**
1. Delete ./scripts/prepForBuild.js

Change to `build:docs`
https://github.com/AlaskaAirlines/auro-input/blob/443a6e02040cbb77b63499d4ff47e4b7f8f873b3/package.json#L150

Delete this file
https://github.com/AlaskaAirlines/auro-input/blob/fajarapri/node18update/.github/ISSUE_TEMPLATE/general-support.md

## Exit criteria 

This issue can be closed once all the aforementioned items have been corrected.

**Comment by fajar-apri-alaska** [comment]
on it
