### ISSUE TITLE
Textbox fill - mixed behaviors - blue or white?

### ISSUE THREAD

**Issue by ashleybiermannalaska** [AlaskaAirlines/auro-input#258]
### Please verify the version of auro-input you have installed

2.13.2

### Please describe the bug

There are two different background colors of the auro-input box to view:

Background is WHITE
1. Go to https://booking-site.ecomm-test-aks.alaskaair.com/order/guests
2. Click into 'Legal first name'
3. Type 'TestOne'
4. Click into 'Middle name'
5. Type 'TestOne'
6. Click into 'Legal last name'
7. Type 'TestOne'
8. Click on page white space to unfocus previous input
9. View those three input background colors to be white

Background is BLUE
1. Go to https://booking-site.ecomm-test-aks.alaskaair.com/order/guests
2. Tab until 'Legal first name' is in focus
3. Use arrow keys to highlight a previously entered value, such as 'TestOne'
4. Press Enter
5. Tab to focus 'Middle name'
6. Use arrow keys to highlight a previously entered value, such as 'TestOne'
7. Press Enter
8. Tab to focus 'Legal last name'
9. Use arrow keys to highlight a previously entered value, such as 'TestOne'
10. Press enter
11. View those three input background colors to be blue

QUESTION: Why are we seeing two different background colors depending on the method used to enter the same text?

![Screenshot 2023-05-31 at 10 32 36 AM](https://github.com/AlaskaAirlines/auro-input/assets/113386737/035dc452-eca6-44fc-8e52-716d97dba103)

![Screenshot 2023-05-31 at 10 32 09 AM](https://github.com/AlaskaAirlines/auro-input/assets/113386737/47e30bcc-04bb-4ca4-8d2b-c415b866b1d6)

### Reproducing the error on the docsite

None

### Expected behavior

Background color of auro-input fields would be the same color when valid, regardless of what method the user used to enter the text. 
method examples: 1. clicking into input and typing new text, 2. tabbing into input, using arrow keys to navigate to a previously entered value, pressing enter to select

### What browsers are you seeing the problem on?

Chrome

### Additional context

- it didn't seem to matter whether the input was required or not required, either way the questionable behavior is found
- if this depends on the browser having previously used values saved, and that causes difficulty, please reach out to me and I can show a screen share demo
- currently unable to repro on Auro docsite, perhaps because there's not a set of inputs together within one form (they are stand alone examples of different use cases)

**Comment by Patrick-Daly-AA** [comment]
This color is controlled by the browser, and not something we see value in changing within Auro.
