### ISSUE TITLE
auro-input: Move Validation functionality to new repo

### ISSUE THREAD

**Issue by Patrick-Daly-AA** [AlaskaAirlines/auro-input#264]
### Is your feature request related to a problem? Please describe.

As the Auro team, we want to reduce redundant code by moving our commonly used validation functions to a new repo so that we are able to more effectively and efficiently maintain our components.

**Comment by jason-capsule42** [comment]
Pending the release of this:

https://github.com/AlaskaAirlines/auro-formvalidation/pull/1

**Comment by jordanjones243** [comment]
This ticket has been completed and can therefore be closed out
