### ISSUE TITLE
Red border on Disabled & Changing the size of the window changes the styling to be `un-disabled`

### ISSUE THREAD

**Issue by dkt2** [AlaskaAirlines/auro-input#274]
### Please verify the version of auro-input you have installed

2.15.1

### Please describe the bug

1. Import `auro-input` into React component
2. Give it the Attribute `disabled`
3. Adjust size of browser window

https://github.com/AlaskaAirlines/auro-input/assets/16234891/fd6fa8c5-a829-4bab-a4c4-cf294462b154

### Reproducing the error on the docsite

This issue cannot be reproduced on the Auro docsite

### Expected behavior

For the border to not be red and not switch to the "un-disabled" color.

### What browsers are you seeing the problem on?

Chrome

**Comment by blackfalcon** [comment]
@dkt2 can you please assist with additional context for this issue?

From the video, you are illustrating that an optional input element that is set to `disabled` has an error UI and after adjusting the browser view it automatically removed the `disabled` state attribute. Is that accurate? 

To assist with this investigation, please include the HTML for how this element is installed in your UI.

**Comment by blackfalcon** [comment]
@dkt2 with some additional looking I was able to discover that locally when running the auro-input element, this happens. 

<img width="1132" alt="Screen Shot 2023-12-26 at 2 08 24 PM" src="https://github.com/AlaskaAirlines/auro-input/assets/181089/fe0d0bb6-ad4d-4492-a39e-f8bee6399037">

It's also clear that this happened with the v2.15.1 release as v2.15.0 does not have this behavior. 

This is the PR https://github.com/AlaskaAirlines/auro-input/commit/c1043b2e6bfdda83b4f989713d6a9042cabd61f9

@fajar-apri-alaska was the author of the update. @jason-capsule42 approved PR.

**Comment by blackfalcon** [comment]
Added context. The auro doc site is referencing the latest version of the input, but I am guessing that there is an element that is loading an older version of the element before it is called in. That is why this issue is not presenting itself on the doc site.

**Comment by fajar-apri-alaska** [comment]
I think I found the issue. PR should be ready today.

**Comment by fajar-apri-alaska** [comment]
I'm not sure about changing the window size that leads to un-disabled styling issue, still looking to find a way to reproduce it in local dev. i'm guessing

**Comment by fajar-apri-alaska** [comment]
I did found wrong disabled border value in 2.15.1, fixes should be in [this PR](https://github.com/AlaskaAirlines/auro-input/pull/276).
