### ISSUE TITLE
setCustomValidityRangeUnderflow value not showing

### ISSUE THREAD

**Issue by cynthiaricomendoza-alaskaair** [AlaskaAirlines/auro-input#275]
### Please verify the version of auro-input you have installed

2.15.0

### Please describe the bug

1. create the following auro-input
```html
<auro-input
   id="birth-date"
   max="12/12/2023"
   min="12/13/2021"
   type="month-day-year"
   setCustomValidityValueMissing="birth date is required"
   setCustomValidityRangeUnderflow="baby cannot be over 2"
   required
   bordered
>
   <span slot="label">Birth date</span>
   <span slot="helptext">Infant's birthdate is required.</span>
</auro-input>
```
2. input a date less than the min value
3. observe the value you set for setCustomValidityRangeUnderflow is not shown under the input box

https://github.com/AlaskaAirlines/auro-input/assets/116121736/68770ad0-5e78-418b-9efa-93111a38ec68

### Reproducing the error on the docsite

This issue cannot be reproduced on the Auro docsite

### Expected behavior

If a user inputs a date less than the min value, the setCustomValidityRangeUnderflow value should be shown under the input box.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

**Comment by blackfalcon** [comment]
@cynthiaricomendoza-alaskaair please schedule some time with @jason-capsule42 and/or @jordanjones243 to review this issue. I am unable to reproduce locally and we need more information about installed context.

**Comment by cynthiaricomendoza-alaskaair** [comment]
@blackfalcon after doing some testing with auro-input and the different versions in our repo, we resolved the issue and are no longer able to reproduce this issue. i also canceled my meeting with @jason-capsule42 and @jordanjones243 with a note letting them know this has been resolved. i think this issue can be closed. thank you!
