### ISSUE TITLE
Updating test runner breaks tests

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-input#279]
### Please verify the version of auro-input you have installed

@latest

### Please describe the bug

When updating `@web/test-runner devDep  0.16.1  ❯  0.18.0`

```
test/auro-input.test.js:

 🚧 Browser logs:
      Lit is in dev mode. Not recommended for production! See https://lit.dev/msg/dev-mode for more information.
      Multiple versions of Lit loaded. Loading multiple versions is not recommended. See https://lit.dev/msg/multiple-versions for more information.
      Element auro-input scheduled an update (generally because a property was set) after an update completed, causing a new update to be scheduled. This is inefficient and should be avoided unless the next update can only be scheduled as a side effect of the previous update. See https://lit.dev/msg/change-in-update for more information.

 ❌ auro-input > clears the value when clicked
      AssertionError: expected undefined to equal ''
        at Ka.<anonymous> (test/auro-input.test.js:64:25)
```

### Reproducing the error on the docsite

This issue cannot be reproduced on the Auro docsite

### Expected behavior

All tests should not fail with updated version of test runners. 

### Additional context

I feel like this is the root of this very related issue 

- https://github.com/AlaskaAirlines/auro-datepicker/issues/183

**Comment by Patrick-Daly-AA** [comment]
need to verify if this is still an issue in the beta branch, as well as potentially in other repos.

**Comment by Patrick-Daly-AA** [comment]
No longer an issue, as confirmed by @jordanjones243
