### ISSUE TITLE
Incorrect fallback value for accent icon

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-input#280]
### Please verify the version of auro-input you have installed

2.15.2

### Please describe the bug

1. Go to https://github.com/AlaskaAirlines/auro-input/blob/main/src/style.scss
2. Scroll down to `.accentIcon` selector
3. Look for `margin-top` rule

<img width="420" alt="Screen Shot 2024-01-09 at 10 40 45 AM" src="https://github.com/AlaskaAirlines/auro-input/assets/55807669/1adb92cf-e3e3-47db-8b39-9b1d6938c3d9">

### Reproducing the error on the docsite

This issue cannot be reproduced on the Auro docsite

### Expected behavior

All tokens have a fallback value with the same value as the token

**Comment by pgm369** [comment]
@Patrick-Daly-AA  I have validated this is a bug!
