### ISSUE TITLE
Show Password button not displaying in Examples, and doesn't display locally

### ISSUE THREAD

**Issue by zmoore-alaskaair** [AlaskaAirlines/auro-input#287]
### Please verify the version of auro-input you have installed

2.17.0

### Please describe the bug

![example not showing button](https://github.com/AlaskaAirlines/auro-input/assets/83420303/39e578de-1252-4cce-a49b-91b344d104b1)
![not displaying when there's an error either](https://github.com/AlaskaAirlines/auro-input/assets/83420303/299fc961-b597-46b4-a366-ea930e73cbab)

### Reproducing the error on the docsite

This issue is reproducible on the Auro docsite

### Expected behavior

There should be an eye icon that toggles between filled and unfilled, open and crossed, when there is content within the  password field.

It looks like there's a previous issue where the problem was resolved, so this may be a regression since then.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

**Comment by Patrick-Daly-AA** [comment]
Currently investigating.  If an urgent workaround is needed, recommend rolling back a version.

**Comment by braven112** [comment]
Still investigating but it appears we aren't triggering this class name `.passwordIcon--show` on the password icon

**Comment by braven112** [comment]
Looks like we removed the necessary class as part of fixing #268

**Comment by braven112** [comment]
Notes for Monday:
We have a [branch ](https://github.com/AlaskaAirlines/auro-input/tree/jbaker/IconRefactorPoc) to simplify the logic but it still needs some CSS and UX changes.
When 2 Icons are showing the padding on the right needs to be 4rem
When 3 Icons are showing the the padding on the right needs to be 6rem
The UX for the eye and when it shows should likely be the same as the X button
The eye icon and X button should show up as soon as there is text in the input.
