### ISSUE TITLE
auro-input: password toggle (eye icon) does not display in svelte app

### ISSUE THREAD

**Issue by CarsonTolleshaug** [AlaskaAirlines/auro-input#30]
## Describe the bug
The eye icon that should display on a password type input field is not visible when the component is rendered in a svelte application. 

## To Reproduce
1. Create svelte app and place an `<auro-input type="password">` on the page (my full component looks like this):
   ```
   <auro-input bind:this={fieldPassword} required="true" type="password" label="Password"></auro-input>
   ```
2. Run app locally
4. Type in the password field

## Expected behavior
Next to the X on the right of the component, an eye icon should be displayed.

## Screenshots
![password](https://user-images.githubusercontent.com/11671889/118737303-6e49c480-b7f9-11eb-88ec-cb31d1a7296d.png)

## Desktop
 - OS: Windows
 - Browser: Chrome
 - Version: 1.3.2

## Additional context
- As you can see in the screenshot, it looks like something is causing the style of the icon to be `visibility: hidden`. 
- The `X` icon displays correctly.

**Comment by blackfalcon** [comment]
The appearance of the icon is based on the focus of the input. When you type into the input element, you should trigger the following selector `:host([type="password"]) .passwordIcon--show .passwordToggle`

<img width="670" alt="Screen Shot 2021-05-19 at 6 17 30 AM" src="https://user-images.githubusercontent.com/181089/118819318-16977180-b86a-11eb-8e6c-59601d069b27.png">

From your screenshot, I can't see the host element 

<img width="603" alt="Screen Shot 2021-05-19 at 6 22 46 AM" src="https://user-images.githubusercontent.com/181089/118819931-a89f7a00-b86a-11eb-8848-8d0d28f44df6.png">

@geoffrich is this another issue where Svelte is not really seeing the attributes of the host element as intended?

**Comment by geoffrich** [comment]
Yeah, if we're using the presence of the type attribute for styling we need to add `reflect: true` to the property inside the custom element. Svelte sets the property instead of the attribute.

**Comment by geoffrich** [comment]
Reflecting the attribute introduced a new issue where the "show password" icon disappears after the first click. This is because the component changes the type from "password" to "text" to show the password, which updates the reflected attribute and breaks the styling. More research is needed to determine the best path forward.

**Comment by geoffrich** [comment]
Shoelace tracks hide/show in a separate state variable instead of updating the type directly. This may fix the issue for us:

```js
type=${this.type === 'password' && this.isPasswordVisible ? 'text' : this.type}
```

https://github.com/shoelace-style/shoelace/blob/916ee072655f33a7c6f603206b4d8eb1c489a34a/src/components/input/input.ts#L305

**Comment by geoffrich** [comment]
As a workaround, you can force setting the attribute using a [Svelte action](https://svelte.dev/docs#use_action):

```html
<script>
	function setPasswordType(node) {
		node.setAttribute('type', 'password');
	}
</script>

<auro-input use:setPasswordType label="password"></auro-input>
```

**Comment by blackfalcon** [comment]
Assuming that @CarsonTolleshaug is ok with the workaround that @geoffrich is proposing, I am going to return this issue to the backlog for a future spring to more closely understand this issue and come up with a solid update.
