### ISSUE TITLE
auro-input not rendering on Svelte

### ISSUE THREAD

**Issue by ArcherScript** [AlaskaAirlines/auro-input#300]
### Please verify the version of auro-input you have installed

2.17.8

### Please describe the bug

1. Create a svelte project
2. Install latest auro-input
3. Add auro-input to html
`Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
    at element`

### Reproducing the error on the docsite

None

### Expected behavior

Input should be renderable on svelte

### What browsers are you seeing the problem on?

Chrome

### Additional context

Works in version 2.16.0. Broken in latest 2.17.8 version. I tried in a new repo, and an existing repo. Reproducible in both scenarios.

**Comment by blackfalcon** [comment]
I believe that this issue will be resolved with this PR

- https://github.com/AlaskaAirlines/auro-input/pull/299

**Comment by blackfalcon** [comment]
I stand corrected, I consulted with @jordanjones243 and it's believed that this is related to an alternate support feature related to dynamically creating DOM elements via JavaScript 

- https://github.com/orgs/AlaskaAirlines/discussions/529

**Comment by jessieiswise** [comment]
Seeing this issue when using it directly from Vue
