### ISSUE TITLE
Updating @aurodesignsystem/auro-formvalidation@1.0.3 breaks all tests

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-input#308]
### Please verify the version of auro-input you have installed

@latest

### Please describe the bug

1. npm update @aurodesignsystem/auro-formvalidation@1.0.3
2. run tests
3. see error stack

### Reproducing the error on the docsite

This issue cannot be reproduced on the Auro docsite

### Expected behavior

When updating to @aurodesignsystem/auro-formvalidation@1.0.3, all tests pass. 

### Exit criteria

This issue can be closed once @aurodesignsystem/auro-formvalidation@1.0.3 is updated and all tests pass successfully.

**Comment by Patrick-Daly-AA** [comment]
@jordanjones243 we're pretty sure you've already got a fix for this in your release branch, feel free to close after verifying
