### ISSUE TITLE
clear btn is enabled when auro-input is disabled and has a value

### ISSUE THREAD

**Issue by cynthiaricomendoza-alaskaair** [AlaskaAirlines/auro-input#309]
### Please verify the version of auro-input you have installed

v2.17.10

### Please describe the bug

1. set a value in the auro-input component
2. then set disabled to true on the auro-input component
3. observe the close btn icon is visible and the value can be cleared in the disabled state

### Reproducing the error on the docsite

This issue is reproducible on the Auro docsite

### Expected behavior

when the auro-input is disabled and there is a value, i would expect the close btn icon to be hidden.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Additional context

here is a screenshot of the behavior in our reservation look up component. the auro-input component is outlined in red. 
<img width="997" alt="Screenshot 2024-05-03 at 14 01 11" src="https://github.com/AlaskaAirlines/auro-input/assets/116121736/a4e378ee-f6c5-4a18-b6b5-fa8b0cb9e009">

I am able to inspect a auro-input component on the auro docsite and add `disabled` to the auro-input component with a value in devtools. here is a screen recording of how i was able to reproduce.
https://github.com/AlaskaAirlines/auro-input/assets/116121736/486fffc3-d066-4729-bfff-428306c49aa8

**Comment by Patrick-Daly-AA** [comment]
Reviewing with UX Design before implementing a fix.

**Comment by leeejune** [comment]
That makes sense. The clear button should also be disabled when the input is disabled.
