### ISSUE TITLE
Address incorrect post-back of generated assets

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-input#314]
### General Support Request

See code

https://github.com/AlaskaAirlines/auro-input/blob/b4b4e08bdce40c4032c27adef4e618f9a9215af7/package.json#L120-L127

### Possible Solution

Update assets object to be correct document names. 

### Additional context

Was updated with commit to previous PR that was closed without merging. 

https://github.com/AlaskaAirlines/auro-input/pull/310/commits/d2886ba2cde9ad6568b5dd3ff9da20e65c1829ed#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

### Exit criteria

This issue can be closed once the assets object has been updated to the correct file names.

**Comment by jason-capsule42** [comment]
File names have already been cleaned up.
