### ISSUE TITLE
auro-input: number type should not trim leading 0s

### ISSUE THREAD

**Issue by zzacal** [AlaskaAirlines/auro-input#355]
### General Support Request

I'm working on a credit card form and have to write javascript to "fix" user input when the value has a leading 0.

#### Some Context

- Month must be in "MM" for the tokenization library
- We want to serve a numeric keyboard so the type is set to `number`

### Issue

When entering months 01-09, the 0 gets trimmed away. 

### I've tried

- Using a `maxLength=2`, but the 0 is still trimmed and I get an immediate error regarding length requirement

### Work around

To get around this, I'm prepending 0 from the input, when necessary, with javascript.

### Possible Solution

Allow leading 0s through an attribute.

### Additional context

![image](https://github.com/user-attachments/assets/35cd28e8-b1cd-41ad-a988-cd595c0b4668)

```tsx
        <auro-input
          name="ExpirationMonth"
          data-testid="cc-exp-month"
          type="number"
          maxLength={2}
          bordered
          required
          value={expirationMonth}
          onInput={updateMonth(setMonth)}
        >
          <span slot="helptext">Expiration month (MM)</span>
          <span slot="label">MM</span>
        </auro-input>
```

### Exit criteria

There is a way to not automatically trim leading 0s

**Comment by Patrick-Daly-AA** [comment]
Will circle back with Design quickly to get alignment on the option of a new input type for month/year that doesn't trim leading 0s

**Comment by Patrick-Daly-AA** [comment]
Also, when we get to engineering side of this, keep in mind auto-fill

**Comment by zzacal** [comment]
Great call out @Patrick-Daly-AA

**Comment by Patrick-Daly-AA** [comment]
@zzacal , @jason-capsule42 will be reaching out to you to talk about your implementation soon-ish

**Comment by zzacal** [comment]
thanks @Patrick-Daly-AA. @jason-capsule42  has given us a path forward. You both rock 🎸
