### ISSUE TITLE
auro-input: DOMException in email input

### ISSUE THREAD

**Issue by denholtz** [AlaskaAirlines/auro-input#41]
## Describe the bug
Typing into an input of type "email" causes an exception:

DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('email') does not support selection.

## To Reproduce
1. Go to http://auro.alaskaair.com/components/auro/input
2. Open the console
3. Scroll to the email input example
4. Type into email input

## Screenshots
<img width="1288" alt="Screen Shot 2021-06-22 at 2 17 07 PM" src="https://user-images.githubusercontent.com/31019257/123000973-16a4f880-d365-11eb-8d58-c9112c78229f.png">

## Desktop (please complete the following information):
 - OS: [MacOS]
 - Browser [chrome, firefox]

## Additional context
This doesn't seem to be breaking anything in production, but is disruptive in at least some development environments. Specifically, this exception crashes the NFP's new Lounge app running from a development server on firefox.

**Comment by blackfalcon** [comment]
@geoffrich this is the code that manages the cursor? This has been a real thorn. We may need to rethink that whole solution?

**Comment by geoffrich** [comment]
Yeah. The Adobe WCs where we took this snippet from only use `type="text"`, so they wouldn't have run into this. I think for now we remove the selection-managing code and re-open #6.

https://github.com/AlaskaAirlines/auro-input/blob/09ee4558af120d8d9781c8a879df4d819187bbb8/src/base-input.js#L168-L173

**Comment by geoffrich** [comment]
Since the exception doesn't appear to have any adverse effects, we are going to swallow the exception for now. The code throwing the exception needs to be there to fix cursor inconsistencies with Safari.
