### ISSUE TITLE
type="number"

### ISSUE THREAD

**Issue by rallyb13** [AlaskaAirlines/auro-input#47]
## Is your feature request related to a problem? Please describe.
We want to use the auro-input for entry of mileage plan numbers. Since these are just numbers, it would be nice to make the input only accept numerals.

## Describe the solution you'd like
Having the input accept a type of "number" (same as the html text input) that prevents acceptance of non-numeric characters.

## Describe alternatives you've considered
Alternatively, we could let them enter non-numeric characters and give them a validation error.
Currently, using my onChange handler to reject non-numeric updates. (Sufficient solution)

## Additional context
I consider this a "nice to have" feature. Current work is not blocked.

For the scope of this feature add, we can use cleave.js to restrict the input of numbers and set the `inputmode` to `numeric` keyboard for virtual keyboards. 

This feature would hijack the native version of `<input type="number">`

## Exit criteria 

This issue will be considered complete once there is a working demo version of the auro-input with `type` `number` that allows only for number entry in conjunction with `maxlength` attribute.

**Comment by blackfalcon** [comment]
If I understand this request correctly, the actual need is an input that will only accept numbers and will produce the number keypad for mobile devices. 

The actual use of the `type="number"` may not be what we want as this introduces a scrolling option that we would have to code away from the experience. 

I'd suggest that we look at using a standard text input and restrict the input and force it to open the keyboard UI.
