### ISSUE TITLE
UI REDESIGN of common interface (next version)

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-input#52]
# General Support Request

The auro-input is being reviewed for a new redesign of the common interface. 

## Support request

Review the current state of the auro-input design and develop a concept for a new interface. 

## Possible Solution

Design to review current UI for new design opportunities 

## Exit criteria 

- [x] complete blueprint work
- [x] signoff from Auro engineering (Dale Sande) 
- [x] signoff by UI designers (Vidal Men)
- [x] consult with Auro engineering team for the creation of dev plan
- [x] add link completed version of auro-input design ([Link](https://www.figma.com/file/ClsrU5j9yHiLA35bq7IRuO/Input?node-id=401%3A287))

## Next steps 

- [x] link new issues(s) from development plan to this design issue 
  - https://github.com/AlaskaAirlines/auro-input/issues/53
- [x] create new issue for the official release of the design blueprint (dependency on completed Auro component). 
  - https://github.com/AlaskaAirlines/AuroDocsSite/issues/58

**Comment by blackfalcon** [comment]
Review new concenpt: https://www.figma.com/file/ClsrU5j9yHiLA35bq7IRuO/Input?node-id=401%3A287

**Comment by leeejune** [comment]
Completed the blueprint draft, but needs 'required' field UI. Will be adding the additional UI to the same file above.

**Comment by leeejune** [comment]
Added 'required' field UI to the same Figma file.

**Comment by blackfalcon** [comment]
@leeejune in reviewing this, for typography there are references like `Body default | 16|24 | Book`

Can you 1:1 that to existing auro tokens? Like I am assuming `var(--auro-text-body-size-default) | var(--auro-text-body-height-default) | var(--auro-text-body-default-weight)`. But that should not be an assumption on my part.

**Comment by leeejune** [comment]
Sure. I don't think I fully understood how the tokens are used for one style of typography... For example, is it correct that Heading 700 @SM 28|34 Book would be a combo of:
`var(--auro-text-heading-700-weight)`
'var(--auro-text-heading-700-px-breakpoint-sm)'
'var(--auro-text-heading-700-size-breakpoint-sm)'
'var(--auro-text-heading-700-height-breakpoint-px-sm)'

**Comment by blackfalcon** [comment]
Where is auro-heading being used in auro-input? 

Using dependency correctly, there should be something that described this type of setting and then the element should only reference that definition, not re-define it again.

**Comment by leeejune** [comment]
Heading is not used, it was just an example to confirm. Issue discussed during a meeting and now is solved!

**Comment by leeejune** [comment]
@blackfalcon Requesting a dev review on the blueprint. Please let me know if there is anything to add/edit.

**Comment by leeejune** [comment]
@vidalmenAS Requesting a design review.

**Comment by blackfalcon** [comment]
@leeejune this looks great. Please update the blueprint to support the current style and we need to reference this new version as a new `outline` style that will be supported with a FEATURE release.

**Comment by vidalmenAS** [comment]
@leeejune reviewed and confirming new design direction approved. Thanks!

**Comment by leeejune** [comment]
Designer has brought up a question:
Does the current doc site support a `password` type input field with an `error` state and `view password` option (eye icon)? The concern is that users will want to see their password if they got the password wrong.

**Comment by blackfalcon** [comment]
@leeejune yes http://auro.alaskaair.com/components/auro/input
<img width="759" alt="Screen Shot 2021-09-02 at 1 22 59 PM" src="https://user-images.githubusercontent.com/181089/131911032-86d611db-61c3-4d4d-a178-a29d82d988a6.png">

**Comment by blackfalcon** [comment]
This looks great. The names `outline` and `underline` feel weird to me. How do you feel about `fill` and `stroke` instead? 

@braven112 we are pretty close to having this be ready for dev work.
