### ISSUE TITLE
auro-input: bug cursor position in Safari

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-input#6]
## Describe the bug
When I move the cursor with the spacebar on iOS and type a letter, the cursor jumps to the end of the input field. 
[Here's a video reproing the issue.](https://github.com/AlaskaAirlines/ods-inputtext/files/5328289/RPReplay_Final1601911061.zip)

## To Reproduce
1. Enter the input field on iOS
2. Type something
3. Move your cursor using the spacebar (or by long-pressing the screen and dragging)
4. Type a letter. The letter is entered in the correct position but the cursor jumps to the end of the field.

## Expected behavior
The cursor does not jump to the end after being manually positioned.

## Smartphone:
 - Device: iPhone 8
 - OS: iOS 13.6
 - Browser: Firefox (i.e. Safari)

**Comment by blackfalcon** [comment]
https://github.com/AlaskaAirlines/auro-input/blob/main/src/base-input.js#L149-L155

That's the issue right there!

**Comment by blackfalcon** [comment]
@geoffrich reactivated the issue. Will queue this up to address later. It's a bug, but it's not a show stopper. 

Isolated the issue down to this function. Have to review its use case and see how we can work around this.

**Comment by blackfalcon** [comment]
Update in progress. See https://github.com/AlaskaAirlines/auro-input/pull/7
