### ISSUE TITLE
Support for type-in date formatting

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-input#72]
Work with @leeejune on the design and functionality....

This is for the functionality we called out in green in our flight search refinement meeting.
![image](https://user-images.githubusercontent.com/5118118/139904629-71ec7881-8690-4378-80c9-17494dc2ba84.png)

In addition to writing in dates for flight searches DD/MM/YYY we'll also need to support MM/YYYY for entering in credit card expiration dates.

**Comment by leeejune** [comment]
Date type of input added to Figma blueprint: https://www.figma.com/file/ClsrU5j9yHiLA35bq7IRuO/Input?node-id=401%3A2756

**Comment by blackfalcon** [comment]
See demo https://input-dateformat-issue72.surge.sh/
