### ISSUE TITLE
If an error attribute is specified, the field always shows as if it has an error

### ISSUE THREAD

**Issue by jeremeevans** [AlaskaAirlines/auro-input#75]
From the documentation page, scroll down to the section about use the error attribute, and you'll see the fields already have an error displayed:
![image](https://user-images.githubusercontent.com/1747006/141216471-d681a536-4776-4485-bb76-e4c10e17e402.png)

Enter something into the field and tab away, and the error is still displayed despite no longer having an error:
![image](https://user-images.githubusercontent.com/1747006/141216580-a3522ef1-fcee-47d7-afbd-d1bb17f8cde2.png)

I would expect the error to not show until after the field has been blurred, and for it to go away after the error is no longer present.

**Comment by blackfalcon** [comment]
In practice, the element does what you expect. The examples you are pointing to are there to simply illustrate the error state without having to trigger the error. 

It's also important to keep in mind that we support an error state on load if the use case called for a refresh of the page with an error returned. 

Here is an example of tabbing out of an input that is required with no content. 

![error-state](https://user-images.githubusercontent.com/181089/141217319-3a8b5517-e923-4070-ba8d-e4890a19faf0.gif)

**Comment by jeremeevans** [comment]
Tabbing out does work, but it does not work if the error attribute is specified. If the error attribute is not specified, the error message is always "Please fill out this field." instead of a more specific error message. Is there a way to specify validators? It could be very useful to define custom validators for things like a PNR.
