### ISSUE TITLE
Add date format input style

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-input#77]
## Is your feature request related to a problem? Please describe.

Date picker uses a unique date input format.

## Describe the solution you'd like

Added UI to the input component that looks like this:

![Screen Shot 2021-11-17 at 2 33 04 AM](https://user-images.githubusercontent.com/55998746/142036125-452373a2-c782-4bc1-81ee-55bb3e835fb0.png)

This input field style will be used specifically for date picker and credit card expiration dates.
[Input Figma Blueprint](https://www.figma.com/file/ClsrU5j9yHiLA35bq7IRuO/Input?node-id=852%3A8770)

**Comment by blackfalcon** [comment]
Is this added to the main branch of the element Figma? If it is, please move this to a branch until we have an opportunity to update the input element to support this. 

What is the floor engineering/design need for this?

**Comment by blackfalcon** [comment]
Am I to assume from this that the desire is to allow users the ability to enter a string date as well as a numeric date? 

<img width="466" alt="Screen Shot 2021-11-16 at 9 59 10 AM" src="https://user-images.githubusercontent.com/181089/142040016-fdb700e1-cf7a-4a9d-9d7b-bf193adde4e2.png">

**Comment by leeejune** [comment]
@blackfalcon The string appears once the date is filled. Users can only type in numeric dates following the given format (MM/DD/YYYY).

**Comment by blackfalcon** [comment]
@leeejune Is this to be an option? I can see where this is a UI for the date picker with selecting a flight, but what about other use cases like entering a date for other things? What about a MM/YYYY for credit cards?

**Comment by leeejune** [comment]
@blackfalcon Is it possible for engineers to customize the formatting? If so, I was thinking that the default can be MM/DD/YYYY and they can customize the format to their needs.

**Comment by blackfalcon** [comment]
Ok... will have to work that into the specification.

**Comment by leeejune** [comment]
I will leave a note in the blueprint as well. Thank you!

**Comment by braven112** [comment]
I think this one is already done, right?

**Comment by blackfalcon** [comment]
yeah, this was never bound to the PR so it never got closed.
