### ISSUE TITLE
auro-input: credit card format

### ISSUE THREAD

**Issue by alaskaryan** [AlaskaAirlines/auro-input#8]
# User story

As a developer, I would like to have the input element updates to support credit cards, so I can easily replicate this experience.

[
![Screen Shot 2020-11-20 at 8 36 50 AM](https://user-images.githubusercontent.com/44302378/99825199-9044e180-2b0b-11eb-9a48-6e6e2b5a3a18.png)
](url)

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [x] Address all design and UX as proposed in the design comp in relation to using Auro specifications
- [x] A11y in regards to role and live notifications need to be coded into the final WC
- [x] Review demo with the designer as well as the Auro team
- [x] All new work to be reviewed by Auro team

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

#### Has been tested in all browsers

- [x] Chrome
- [ ] Firefox
- [ ] Edge (79 +)
- [x] Safari
- [ ] Mobile Safari
- [ ] IE11

#### Has been tested for accessibility

- [x] Screenreader
- [ ] Axe
- [x] Keyboard use

#### Performance

- [ ] Chrome Lighthhouse report

#### Auro component features

- [x] README doc completed with all relative information
- [x] API documentation created
- [ ] Bundled version tested and documented
- [x] Examples and use case info created
- [ ] Pages added to the Auro Doc Site

## Audit

https://github.com/AlaskaAirlines/auro/issues/127

**Comment by blackfalcon** [comment]
@alaskaryan  thanks for this! Is there a design spec in Figma or Sketch that we can attach to this? Has this artwork been included or considered for inclusion with the UI KIt?

**Comment by alaskaryan** [comment]
@blackfalcon  here is what we have so far in Figma 
[](https://www.figma.com/file/VpUz89Ov6ImBpY5YvzYbZW/Auro-toolkit?node-id=0%3A1918)

**Comment by alaskaryan** [comment]
Updated: https://www.figma.com/file/fYDbVhBXe2eiknYxxZFS4f/Input-fields?node-id=0%3A1
