### ISSUE TITLE
Number formatting for v2.2-rc

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-input#81]
## NEXT MINOR release 

The following items are to be included with the next MINOR release of the auro-input element all PRs are to be from the feature branch to `v2.2-rc` branch.

Support an optional max length to input types to allow for confirmation code and MileagePlan number validation
>- [ ] Confirmation Code Validation (Carentee) 6 letters
>- [ ] MileagePlan number Validation (Carentee) 9 numbers 
>- [ ] Help (Consult) Loyalty team implement auro inputs in promo space.
>- [ ] Known Traveler number (TSA Precheck #/Redress number) 

Date formatting
>- [ ] #93 Additional context #77

**Comment by blackfalcon** [comment]
Release issues are no longer being maintained.
