### ISSUE TITLE
Finalized Date Formatting added to the input blueprint on a feature branch

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-input#82]
Looks like the current [blueprint](https://www.figma.com/file/ClsrU5j9yHiLA35bq7IRuO/Input?node-id=401%3A287) doesn't match what Kayla had for the fully written out format.  I think we landed on a solution where the day of the week is last.  

We also want to think about how we want this formatted if it is a credit card expiration.  Do we want to convert the MM/YYYY format to a written format as well?

Our development plan is to release a version that supports MM/DD/YYYY and MM/YYYY.  Then after that is completed and released, we will release a version that transforms the MM/DD/YYYY format into the written out version.  Depending on what we learn about CC expiration we can release both changes at the same time or independently.

**Comment by leeejune** [comment]
![Screen Shot 2021-11-23 at 7 50 31 AM](https://user-images.githubusercontent.com/55998746/142950561-7fd15185-b528-4f66-b194-6c009eea558b.png)

Made edits to the component. Note added to address alternative date formatting options.

**Comment by blackfalcon** [comment]
This issue was moved to `done` but not closed? Is this still an open issue?
