### ISSUE TITLE
double pain/pane input

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-input#83]
## Is your feature request related to a problem? Please describe.

In uses cases where a date range is needed we would like to have an input that accepts two values.

## Describe alternatives you've considered

Using 2 separate inputs could also work but it would be harder to visualize the range of dates.

## Additional context

This would be used in selecting round trip flights.

**Comment by blackfalcon** [comment]
The UI you are looking for would not be a single input interface to support. What we would build is a new component, e.g. datepicker, that would have two instances of auro-input.
