### ISSUE TITLE
Support clearing field during error state

### ISSUE THREAD

**Issue by Dayna-A** [AlaskaAirlines/auro-input#86]
## Is your feature request related to a problem? Please describe.
Requesting an option to clear the field when the current input in the field is producing an error message. Today the 'x' to clear is only available while editing a field that is not in an error state, however that might be just the moment a user wants to clear away their mistake and restart.Ex. User typed their name into the email field by mistake.

![clearInputOnError](https://user-images.githubusercontent.com/35708093/143141686-90bb0295-dbcb-4067-9df2-57095753ae67.png)

## Describe the solution you'd like
Would like us to find a a user friendly way to include a 'clear button' during error state, rather than just replacing the x with the error icon'

## Describe alternatives you've considered

One of our designers was mulling over adding the 'x' to the left of the error icon in this situation. We would value proper design research though.

## Additional Context

This seems especially helpful to improve the user experience on mobile devices whose keyboards take longer to use.

**Comment by blackfalcon** [comment]
@Dayna-A 100% hear you. The current design spec defines that when there is an error, the only icon that appears is the alert icon. To move forward on this, we will need to consult with the design team to update this spec. 

<img width="1527" alt="Screen Shot 2021-11-23 at 4 11 10 PM" src="https://user-images.githubusercontent.com/181089/143148310-8fb78837-b6d3-4324-96ac-8c0b56b81d90.png">

**Comment by blackfalcon** [comment]
> One of our designers was mulling over adding the 'x' to the left of the error icon in this situation.

Can this person reach out to @leeejune to discuss options?

**Comment by leeejune** [comment]
Kaitlin Reiss will be working on gathering UX research on the placement of 'x'.

**Comment by leeejune** [comment]
https://www.figma.com/file/AVOmkx7dRpFWJjajqXGHsn/wow-random?node-id=0%3A1

Explorations have been done in the link above. We decided that adding an "X" clear button may not be a priority. However, it might be better to make the "eye" icon button persistent even in password error states. See screenshot below. Will work on this again in Jan.

Current behavior of password field: 

1. Default state
2. User enters password (ACTIVE)
3. User submits incorrect password (ERROR)
4. User clicks into input to enter new password (ERROR)
4. User submits correct password (ACTIVE)

![Screen Shot 2021-12-18 at 6 34 17 AM](https://user-images.githubusercontent.com/55998746/146610601-68943f15-8560-458e-b1b7-32b45f955e3b.png)

**Comment by blackfalcon** [comment]
> However, it might be better to make the "eye" icon button persistent even in password error states.

This is already true. The hide/show password icon appears based on `:focus`. 

<img width="1115" alt="Screen Shot 2021-12-17 at 3 46 49 PM" src="https://user-images.githubusercontent.com/181089/146620133-302447ed-4e6e-40da-9dfa-0478d702fc1a.png">

But as you point out, with an error state that would mean showing 3 icons. 

But this raises the question, what is the scenario where we would only show an error with the password? WIth a username/password combination, we would never state that as an individual fail. The whole login would be a fail. 

There is also another part of this. There is the auroLabs version of `changepassword` that has a very specific scenario 

<img width="1044" alt="Screen Shot 2021-12-17 at 4 03 10 PM" src="https://user-images.githubusercontent.com/181089/146621062-b8fb533f-ea9a-4d5a-ad4f-381a8d14ae55.png">

**Comment by blackfalcon** [comment]
This idea BTW was pretty much a copy/paste from SBX. 

<img width="499" alt="Screen Shot 2021-12-17 at 4 08 27 PM" src="https://user-images.githubusercontent.com/181089/146621313-73bafa27-c539-469e-9425-c74c45fda496.png">

**Comment by leeejune** [comment]
Concluded that the clear state is not necessary for other inputs (other than passwords) on a web platform. If an input for mobile is developed, we will be considering adding a clear button at any state. However, it was discussed that it is more work for the user to click on a clear state than to delete the error with their keyboard.
