### ISSUE TITLE
Support field clearing in error state

### ISSUE THREAD

**Issue by Dayna-A** [AlaskaAirlines/auro-input#87]
## Is your feature request related to a problem? Please describe.

Requesting an option to clear the field when the current input in the field is producing an error message. Today the 'x' to clear is only available while editing a field that is not in an error state, however that might be just the moment a user wants to clear away their mistake and restart.Ex. User typed their name into the email field by mistake.
![clearInputOnError](https://user-images.githubusercontent.com/35708093/143141686-90bb0295-dbcb-4067-9df2-57095753ae67.png)

## Describe the solution you'd like
Would like us to find a a user friendly way to include a 'clear button' during error state, rather than just replacing the x with the error icon'

## Describe alternatives you've considered

One of our designers was mulling over adding the 'x' to the left of the error icon in this situation. We would value proper design research though.

## Additional Context

This seems especially helpful to improve the user experience on mobile devices whose keyboards take longer to use.

**Comment by braven112** [comment]
@Dayna-A Is this one the same as #86 ?

**Comment by blackfalcon** [comment]
This issue is a duplicate, but there is a difference in content. @Dayna-A can you help us consolidate this into a single issue?

**Comment by Dayna-A** [comment]
@blackfalcon & @braven112  sorry I was having internet issues yesterday and it told me it wasn't successfully created the first time. I will consolidate. Thanks.
