### ISSUE TITLE
onDark theme doesn't change color of the X clear value icon

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-input#92]
## To Reproduce

1. Use `<auro-input onDark />`
1. Enter a value in the input
1. Examine the X clear icon

## Expected behavior

The icon should not be black, it should be `--auro-color-icon-disabled-on-dark`

**Comment by blackfalcon** [comment]
@jason-capsule42 auro-input doesn't support `ondark`? 

https://auro.alaskaair.com/components/auro/input/api

**Comment by blackfalcon** [comment]
auro-input onDark should be removed from the element with v3.0 and then we can look to adding better dark mode support.

**Comment by Patrick-Daly-AA** [comment]
Fixed in Beta with our theming related work.
