### ISSUE TITLE
Convert Date to written format

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-input#93]
## Is your feature request related to a problem? Please describe.

As a follow up to this story #89, we would also like to have the option to convert the MM/DD/YYYY style format into the written out format referenced in this #82

## Describe the solution you'd like

After a user enters the date in the MM/DD/YYYY format it will change to a fully written out format once the user removes focus from the element.

## Describe alternatives you've considered

Leave it as is

## Additional context

This piece of work should probably be optional but would primarily be used in conjunction with the date picker
- #77

**Comment by blackfalcon** [comment]
@leeejune can you provide any updated context to this request? Is this still desired or has this been dismissed?

**Comment by leeejune** [comment]
@blackfalcon Currently there is no request for this. I think this came from the idea of date formatting differently in the date picker component. This idea can be revisited; I think it is desired still.
