### ISSUE TITLE
auro-input voice over should read labels before value

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-input#96]
## To Reproduce

1. Go to demo page
1. Enter a value for any input
1. Move keyboard focus off of the input
1. turn on your systems text to speech
1. Move keyboard focus onto the input
1. Observe the spoken information regarding the input

"Twelve Twenty One Two Thousand Twenty One, Arrival Date"

Moving the label element above the input in the DOM would likely resolve this issue since the screenreaders announce elements in DOM order.

I'm not sure if helper text should also be read before the value or not. The only reason I have to think it should be is that reading it after the value could be confusing in that it may appear as part of the value in some cases. Perhaps Helper Text is only read when there is no value or there is an error?

**Comment by geoffrich** [comment]
I can't repro this in iOS VoiceOver. For the basic input, "Name (optional)" is read before the value.

https://user-images.githubusercontent.com/4992896/144466922-4b44389b-e9a2-4e69-b8fe-c17214cec212.mp4


> Moving the label element above the input in the DOM would likely resolve this issue since the screenreaders announce elements in DOM order.

I don't think that's the case -- when focusing an input, screen readers should read out the associated label at the same place, regardless of where the label is in the DOM (the label could be in a completely different part of the page).

> I'm not sure if helper text should also be read before the value or not. The only reason I have to think it should be is that reading it after the value could be confusing in that it may appear as part of the value in some cases. Perhaps Helper Text is only read when there is no value or there is an error?

AFAIK helper text is working as expected. We're associating it with the input via `aria-describedby`. It's up to the screen reader how it wants to announce it -- we shouldn't try to change that. DOM order shouldn't have an effect.

**Comment by blackfalcon** [comment]
I understand what you are saying. This is expected behavior. 

When a user first comes to a form field, it reads like the following. This is because the input value is empty. 

<img width="742" alt="Screen Shot 2021-12-02 at 12 25 52 PM" src="https://user-images.githubusercontent.com/181089/144497948-95911234-8513-4369-a6c4-04015c2d3669.png">

But after a value is entered, when clicking into or tabbing back, the value in the input is read first. 

Changing the order of the DOM elements will not change this.

**Comment by braven112** [comment]
We reviewed and current behavior meets HTML spec.
