### ISSUE TITLE
Design Formatting of numbers

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-input#98]
## Design story

In order to support formatting of phone numbers or mileage plan numbers we would like to consider how the mobile and desktop experience should be.

### Questions to answer:
In mobile devices should the input default to the number pad.
What about on desktop?
How do we handle country codes?
Are there other scenario's where we would expect users to input numbers into an auro-input?
Are there any learnings from Credit Card numbers that should also apply here?

### Additional Context
This design story came out of the refinement of these 2 issues.  Once this design research is complete and designs are ready we can begine work on these two stories below.
>- [ ] https://github.com/AlaskaAirlines/auro-input/issues/47 
>- [ ] #78

**Comment by leeejune** [comment]
Will be meeting with @shelbyevans to discuss this.

**Comment by leeejune** [comment]
Talked to Shelby about this. Need further explorations on combination of input and dropdown.

**Comment by blackfalcon** [comment]
@leeejune if I am understanding this correctly, this issue has no resolution and can be closed.
